### PR TITLE
builtin/*: update usage format

### PR DESCRIPTION
**Pull request by adlternative**
According to the "Error Messages" section of
Documentation/CodingGuidelines, we should not end in a full
stop or start with a capital letter. Fix old error and usage
messages to match this expectation.

Signed-off-by: adl <1607364851@qq.com>
cc: Felipe Contreras <felipe.contreras@gmail.com>
cc: Derrick Stolee <stolee@gmail.com>

### CODE REVIEW

**Comment by dscho** [comment]
Please use your real name in the `Signed-off-by` footer (as well as in your author information). The Git project insists on it.

**Comment by adlternative** [comment]
> Please use your real name in the `Signed-off-by` footer (as well as in your author information). The Git project insists on it.

ok,I I just misunderstood what you meant, now I understand that I must use my real name, I'll change it

**Pull request closed without merging**
