### PR TITLE
[PATCH] trace: use prefix from startup_info

### PR DESCRIPTION
**Pull request by torilov**
trace.h: update trace_repo_setup signature
trace.c: update trace_repo_setup implementation
git.c: update trace_repo_setup usage

I'm new to git, I want to try to make a test contribution.

cc: Torsten Bögershausen <tboegi@web.de>

### CODE REVIEW

**Comment by dscho** [comment]
Could you please use another prefix than "chore"? Git prefers an area (e.g. "tests:"), Git Flow is not used.

**Comment by torilov** [comment]
Sorry about that, I corrected the title. Thank you!

**Comment by torilov** [comment]
Ok, I didn't get it. I had to rename the commit itself to make description prefix more convenient. Sorry.

**Comment by dscho** [comment]
> 
> 
> Ok, I didn't get it. I had to rename the commit itself to make description prefix more convenient. Sorry.

My fault, I did not express myself very clearly. Sorry about that! In any case, you got a good (and pretty excited!) review from the Git maintainer themselves. Meaning: you piqued the interest and some praise. Congratulations!

**Pull request closed without merging**
