### PR TITLE
[QUIMBY] CI run for git-hook on top of master

### PR DESCRIPTION
**Pull request by nasamuffin**
This pull request was created by https://github.com/nasamuffin/quimby, a tool for Git contributors who are accustomed to a git-format-patch/git-send-email workflow but want to see the GitGitGadget CI run results. It should probably be ignored!

(Formatting test for git-mentoring help. Ignore me.)

test1
test2
test3

- test4
- test5
- test6

 - test7
 - test8
 - test9

### CODE REVIEW

**Comment by dscho** [comment]
I'm confused. Doesn't `master` already remove support for Azure Pipelines in favor of GitHub workflows?

**Comment by nasamuffin** [comment]
It's not so complicated as that. This PR is extremely stale and I should have closed it; I was using it only to test formatting changes for a question on the mentoring list.

**Pull request closed without merging**
