### PR TITLE
builtin add -p: fix hunk splitting

### PR DESCRIPTION
**Pull request by phillipwood**
Thanks to Junio and Ævar for their comments on V1. I've updated the commit message and added a helper function as suggested.

V1 Cover Letter:
Fix a small regression in the hunk splitting of the builtin version compared to the perl version. Thanks to Szeder for the easy to follow bug report.

Cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>
Cc: SZEDER Gábor <szeder.dev@gmail.com>
cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Phillip Wood <phillip.wood123@gmail.com>

### CODE REVIEW

**Comment by dscho** [comment]
@phillipwood please ignore [the macOS failure](https://github.com/gitgitgadget/git/runs/4581311473?check_suite_focus=true#step:3:92) for now (I believe the culprit is an incorrectly-cached Homebrew package, not a bug in your PR.

**Comment by phillipwood** [comment]
> @phillipwood please ignore [the macOS failure](https://github.com/gitgitgadget/git/runs/4581311473?check_suite_focus=true#step:3:92) for now (I believe the culprit is an incorrectly-cached Homebrew package, not a bug in your PR).

Thanks @dscho, yes it looks like there is a problem installing perforce.

**Comment by dscho** [comment]
> it looks like there is a problem installing perforce.

Yes, and my PR was merged that fixed it.

**Pull request closed without merging**
