### PR TITLE
git-mergetool: improve error code paths and messages

### PR DESCRIPTION
**Pull request by phil-blain**
Changes in v2:
As suggested by Junio:
- 3/5: moved the error message to setup_tool itself, and adjusted the commit message
- 3/5: made the test more robust
- 4/5: adjusted the error message

v1:
These are a few improvements to improve existing error messages in 'git mergetool', and make sure that errors are not quiet, along with a small completion update in 1/1.

CC: Seth House <seth@eseth.com>
CC: David Aguilar <davvid@gmail.com>
CC: Johannes Sixt <j6t@kdbg.org>

### CODE REVIEW

**Comment by phil-blain** [comment]
Hi @dscho !

My first two tries ([one](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=228461&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=6c0dc9a0-5e79-5d03-2eb1-7a6d7e4ff35d&l=16), [two](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=228462&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=6c0dc9a0-5e79-5d03-2eb1-7a6d7e4ff35d&l=16
)) at `/submit` failed because (if I understand correctly) the node.js v18.20.5 released today was not yet up at https://nodejs.org/dist/v18.20.5/, although the folder existed already. I guess this is just bad luck and there is nothing much Gitgitgadget can do ? And changes would need to go into the `NodeTool` Azure task to make it more robust ?

**Comment by dscho** [comment]
> My first two tries ([one](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=228461&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=6c0dc9a0-5e79-5d03-2eb1-7a6d7e4ff35d&l=16), [two](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=228462&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=6c0dc9a0-5e79-5d03-2eb1-7a6d7e4ff35d&l=16)) at `/submit` failed because (if I understand correctly) the node.js v18.20.5 released today was not yet up at https://nodejs.org/dist/v18.20.5/, although the folder existed already. I guess this is just bad luck and there is nothing much Gitgitgadget can do ? And changes would need to go into the `NodeTool` Azure task to make it more robust ?

@phil-blain sorry for the woes! Your analysis is indeed correct.

I now changed the Pipeline definition to use v1 of that task (instead of v0), and I checked off the "Check for Latest Version" checkbox. That should be good enough.

**Pull request closed without merging**
