### PR TITLE
Simple IPC Mechanism

### PR DESCRIPTION
**Pull request by jeffhostetler**
Here is version V7 of my simple-ipc series.  The only change from V6 is to squash in
the CALLOC_ARRAY() suggestion.

 $ git range-diff v2.31.0-rc1..pr-766/jeffhostetler/simple-ipc-v6 v2.31.0-rc1..HEAD
 1:  fe35dc3d29 =  1:  fe35dc3d29 pkt-line: eliminate the need for static buffer in packet_write_gently()
 2:  de11b30361 =  2:  de11b30361 pkt-line: do not issue flush packets in write_packetized_*()
 3:  3718da39da =  3:  3718da39da pkt-line: add PACKET_READ_GENTLE_ON_READ_ERROR option
 4:  b43df7ad0b =  4:  b43df7ad0b pkt-line: add options argument to read_packetized_to_strbuf()
 5:  f829feb2aa =  5:  f829feb2aa simple-ipc: design documentation for new IPC mechanism
 6:  58c3fb7cd7 =  6:  58c3fb7cd7 simple-ipc: add win32 implementation
 7:  4e8c352fb3 =  7:  4e8c352fb3 unix-socket: eliminate static unix_stream_socket() helper function
 8:  3b71f52d86 =  8:  3b71f52d86 unix-socket: add backlog size option to unix_stream_listen()
 9:  5972a19836 =  9:  5972a19836 unix-socket: disallow chdir() when creating unix domain sockets
10:  02c885fd62 = 10:  02c885fd62 unix-stream-server: create unix domain socket under lock
11:  4c2199231d ! 11:  eee5f4796d simple-ipc: add Unix domain socket implementation
    @@ compat/simple-ipc/ipc-unix-socket.c (new)
     +  pthread_cond_init(&server_data->work_available_cond, NULL);
     +
     +  server_data->queue_size = nr_threads * FIFO_SCALE;
    -+  server_data->fifo_fds = xcalloc(server_data->queue_size,
    -+                                  sizeof(*server_data->fifo_fds));
    ++  CALLOC_ARRAY(server_data->fifo_fds, server_data->queue_size);
     +
     +  server_data->accept_thread =
     +          xcalloc(1, sizeof(*server_data->accept_thread));
12:  132b6f3271 = 12:  8b5dcca684 t0052: add simple-ipc tests and t/helper/test-simple-ipc tool

Jeff

cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Jeff Hostetler <git@jeffhostetler.com>
cc: Jeff King <peff@peff.net>
cc: SZEDER Gábor <szeder.dev@gmail.com>
cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>
cc: Chris Torek <chris.torek@gmail.com>

### CODE REVIEW

**Comment by jeffhostetler** [comment]
PR 766 is based upon v2.29.0 whereas 717 was based on v2.28.0+strvec.

**Comment by dscho** [comment]
> PR 766 is based upon v2.29.0 whereas 717 was based on v2.28.0+strvec.

For the record, if you hit <kbd>Edit</kbd> next to the PR title, it lets you re-target the PR to another branch.

**Comment by jeffhostetler** [comment]
This force-push moves the base to v2.30.0.

**Pull request closed without merging**
