### PR TITLE
Fixup for js/mingw-o-append

### PR DESCRIPTION
**Pull request by jeffhostetler**
The recent change mingw O_APPEND change breaks writing to named
pipes on Windows.  The first commit adds a new test to confirm the
breakage and the second commit fixes the problem.  These could be
squashed together or we can just keep the fix and omit the test if that
would be better.

d641097589 (js/mingw-o-append) mingw: enable atomic O_APPEND

The new mingw_open_append() routine successfully opens the client
side of the named pipe, but the first write() to it fails with EBADF.
Adding the FILE_WRITE_DATA corrects the problem.

 Signed-off-by: Jeff Hostetler <jeffhost@microsoft.com>

Cc: j6t@kdbg.org
Cc: johannes.schindelin@gmx.de
Cc: gitster@pobox.com
Cc: peff@peff.net
Cc: jeffhost@microsoft.com

### CODE REVIEW

**Comment by stefanbeller** [comment]
https://public-inbox.org/git/pull.35.v3.git.gitgitgadget@gmail.com/
seems to have broken the Cc chain. (no new line between CCs and only two show up)

**Comment by dscho** [comment]
This branch is now known as [`js/mingw-o-append`](https://github.com/gitster/git/commits/js/mingw-o-append).

**Comment by dscho** [comment]
This patch series was integrated into pu via https://github.com/git/git/commit/e3d4ff037db41234eaf74167ab7d1a443c23243d.

**Comment by dscho** [comment]
This patch series was integrated into next via https://github.com/git/git/commit/e3d4ff037db41234eaf74167ab7d1a443c23243d.

**Comment by dscho** [comment]
This patch series was integrated into master via https://github.com/git/git/commit/e3d4ff037db41234eaf74167ab7d1a443c23243d.

**Comment by dscho** [comment]
Closed via e3d4ff037db41234eaf74167ab7d1a443c23243d.

**Pull request closed without merging**
