### PR TITLE
doc: git diff reformatting

### PR DESCRIPTION
**Pull request by jnavila**
This is the continuation of the editing of the manpages to reflect the new formatting rules.

Changes since V3:

 * rework the description about `-1`, `--base`,...

cc: Johannes Sixt <j6t@kdbg.org>
cc: Patrick Steinhardt <ps@pks.im>

### CODE REVIEW

**Comment by jnavila** [comment]
Hello @dscho

It seems I can no longer submit this PR, the gitgitgadget bot does not react to the submit commentaries.

**Comment by dscho** [comment]
Hmm. It all started [yesterday](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=228187&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=fd9d79e0-dc99-51c0-4ec1-8ae1b7984af2&l=19).

**Comment by jnavila** [comment]
The log seems to indicate some kind of conflict while trying to run Git in parallel, which is quite strange, given that this part is just supposed to clone the project.

**Comment by dscho** [comment]
> The log seems to indicate some kind of conflict while trying to run Git in parallel, which is quite strange, given that this part is just supposed to clone the project.

Indeed. In [the first failing build](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=228187&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=fd9d79e0-dc99-51c0-4ec1-8ae1b7984af2&l=16) the `find` call did not find any `.lock` files, even. So it must be some race within the `git reset --hard` call itself. I added `GIT_TRACE2_PERF` tracing just in case, hoping that it will help us by identifying threads and/or processes that might try to lock that file simultaneously.

**Pull request closed without merging**
