### PR TITLE
[Outreachy] documentation: remove empty doc files

### PR DESCRIPTION
**Pull request by HebaWaly**
Remove empty and redundant documentation files from the
Documentation/technical/ directory.

The empty doc files included only TODO messages with no documentation for 
years. Instead an approach is being taken to keep all doc beside the code 
in the relevant header files.
Having empty doc files is confusing and disappointing to anybody looking 
for information, besides having the documentation in header files makes it 
easier for developers to find the information they are looking for.

Some of the content which could have gone here already exists elsewhere:
- api-object-access.txt -> sha1-file.c and object.h have some details.
- api-quote.txt -> quote.h has some details.
- api-xdiff-interface.txt -> xdiff-interface.h has some details.
- api-grep.txt -> grep.h does not have enough documentation at the moment.

Signed-off-by: Heba Waly <heba.waly@gmail.com>

### CODE REVIEW

**Comment by dscho** [comment]
Seems [the CI build fails](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=18804&view=logs&jobId=253e5128-1058-5bd4-fdf1-9b556d3207f8&taskId=95c65aec-3627-54dc-fc17-47625f123bb3&lineStart=757&lineEnd=758&colStart=1&colEnd=45):

```
[...]
make[1]: *** No rule to make target 'technical/api-index-skel.txt', needed by 'technical/api-index.txt'.  Stop.
make[1]: *** Waiting for unfinished jobs....
```

**Comment by dscho** [comment]
> Remove empty documentation files from the Documentation/technical/
> directory, as these files include only todo messages with no documentation
> added.
> 
> Signed-off-by: Heba Waly [heba.waly@gmail.com](mailto:heba.waly@gmail.com)
> 
> Thanks for taking the time to contribute to Git! Please be advised that the
> Git community does not use github.com for their contributions. Instead, we use
> a mailing list ([git@vger.kernel.org](mailto:git@vger.kernel.org)) for code submissions, code reviews, and
> bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
> to conveniently send your Pull Requests commits to our mailing list.
> 
> Please read the "guidelines for contributing" linked above!

Please also note that the PR description will be sent as cover letter. Maybe you want to change it a little? :smile:

**Comment by HebaWaly** [comment]
> > Remove empty documentation files from the Documentation/technical/
> > directory, as these files include only todo messages with no documentation
> > added.
> > Signed-off-by: Heba Waly [heba.waly@gmail.com](mailto:heba.waly@gmail.com)
> > Thanks for taking the time to contribute to Git! Please be advised that the
> > Git community does not use github.com for their contributions. Instead, we use
> > a mailing list ([git@vger.kernel.org](mailto:git@vger.kernel.org)) for code submissions, code reviews, and
> > bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
> > to conveniently send your Pull Requests commits to our mailing list.
> > Please read the "guidelines for contributing" linked above!
> 
> Please also note that the PR description will be sent as cover letter. Maybe you want to change it a little? 😄

Right! Thanks 😄

**Pull request closed without merging**
