### PR TITLE
In-core `git merge-tree` ("Server side merges")

### PR DESCRIPTION
**Pull request by newren**
Sorry for the long delay.  Much thanks to Johannes for tying up the loose ends and making several improvements seen in this round.  Note: rebased on main (it's been 4 months since v6, and there were a few conflicts...).

== Basic Summary ==

This series introduces a new mode to `git merge-tree` allowing it to perform real merges (three-way text content merges, recursive ancestor consolidation, rename detection, proper directory/file conflict handling, etc.) and write the result as a toplevel tree.  It doesn't touch the working tree or index, and doesn't create any commits or update any refs.  It could be used to do merges when in a bare repository (thus potentially making it of interest to Git hosting sites, i.e. "Server side merges"), or for doing a merge of branches that aren't checked out.

It does not handle similar functionality for cherry-picks, rebases, or reverts; that is also of interest, but is being deferred for a future series.

== Quick Overview ==

* Patches 1-2: preparatory cleanups
* Patches 3-4: implement basic real merges
* Patches 5-6: include informational messages ("CONFLICT" messages and such) in output
* Patches 7-15: add ability to include `ls-files -u` style of info in the output
* Patch 16: support `--allow-unrelated-histories`
* Patch 17: augment the manual with potential usage mistakes

== Updates Log ==

Stuff NOT included that reviewers brought up in various rounds (and which might still be an open question):
  * Very generic (mode, oid, stage, filename) printing formatting[3]
  * Providing similar functionality for doing cherry-picks/rebases/reverts, i.e. a scheme for three-way merges with a specified merge-base[4].  That's being deferred to a future series.
[3] https://lore.kernel.org/git/CABPp-BGnOes7J_piDyBUeuLVm274w4-9G3k0vR-0it3z7TPn_w@mail.gmail.com/
[4] https://lore.kernel.org/git/CABPp-BEaemkGGm0cSofP0gau7YN-y6HFoi0yJbHA8+iGjxsYSA@mail.gmail.com/

Updates since v6:
  * Significant merge-ort changes to support machine-parseable information about individual conflicts and the paths involved in each, rather than just a group of free-form output messages that may change over time.  This includes 5 new patches, 2 written by Johannes (and with breaking out the other 3 from some work-in-progress changes I had including some fixes and improvements he added). 

Updates since v5:
  * Used reverse_commit_list() to reverse a commit_list without extra allocations
  * Several documentation updates

Updates since v4:
  * Fixed double "is" in documentation.
  * Fixed a few small items with testcases

Updates since v3:
  * Dropped previous patches 5, 6, and 8 of the old series; they weren't being used and opened a can of worms[1]
  * [Patch 3] Restructured argument checking, including using an enum
  * [Patch 4] Restored the extended paragraph about the deprecated form of git-merge-tree, mentioned write-tree in plumbing commands, and a few other small fixups to the documentation
  * [Patch 4] Also provide an example of a clean merge rather than just a conflicted one
  * [Patch 6] Fix the incompatible arguments check and add some tests for it
  * [Patch 6] Introduce an anonymize_hash() shell function to make tests easier to read (less repeated sed)
  * [Patch 9] Rename --exclude-modes-oids-stages to --name-only; no short option for now
  * [Patch 10] When -z passed, the tree in the first section should have a trailing NUL rather than trailing newline
[1] https://lore.kernel.org/git/CABPp-BEKuXHELVx4=5JJTj5HVOKZ=Y-4G4BK47BCZYYRSrkFsQ@mail.gmail.com/

Updates since v2:
  * Improved patches from Dscho for the diff_warn_rename_limit() handling
  * Add a -z option for NUL-terminated conflict info lines (so that filenames do not have to be quoted)

Updates since v1 (or v3 depending on how you count; thanks to René, Ævar, Christian, Dscho for very helpful feedback):
  * New patch from Dscho allowing diff_warn_rename_limit() to print somewhere other than stdout (I hope he's okay with me including his Signed-off-by)
  * Now prints filenames relative to prefix, much like ls-files
  * Renamed --exclude-oids-and-modes to --exclude-modes-oids-stages and gave it a -l shorthand; I'm wondering if I should just drop this option, though.
  * And numerous cleanups, in lots of areas:
    * Multiple parse-options cleanups
    * Lots of commit message cleanups
    * Wording tweaks to the "Description" section of the manual
    * Several small code cleanups
  * I dropped the RFC label

[There were also two submissions of a previous series; see https://lore.kernel.org/git/pull.1114.v2.git.git.1641403655.gitgitgadget@gmail.com/]

Updates since original submission v2 (thanks to Christian, Dscho, Ramsay, and René for suggestions and comments):
  * Significant changes to output format:
    * Flags no longer take a filename for additional output; they write to stdout instead.
    * More information included by default when there are conflicts (no need to request it with additional flags, instead flags can be used to suppress it).
    * Provide (mode, oid, stage, file) tuples -- i.e. `ls-files -u` style of information -- when there are conflicts.  Add a flag to only list conflicted files if that's preferred.
  * Much more thorough manual for git-merge-tree.txt
  * Renamed option from `--real` to `--write-tree`
  * Accept an optional `--trivial-merge` option to get old style merge-tree behavior
  * Allow both `--write-tree` and `--trivial-merge` to be omitted since we can deduce which from number of arguments
  * Document exit code when the merge cannot be run (so we can distinguish other error cases from conflicts)
  * testcase cleanups: test_tick, early skip of test when using recursive backend, variable renames, etc.
  * various minor code cleanups
  * Add a new --allow-unrelated-histories option (with same meaning as the one used in `git merge`)
  * Rebased on top of en/remerge-diff to avoid a small conflict

Updates since original submission v1 (thanks to Johannes Altmanninger and Fabian for suggestions):
  * Fixed a bad patch splitting, and a style issue pointed out by Johannes Altimanninger
  * Fixed misleading commit messages in new test cases
  * Fixed my comments about how commit-tree could be used to correctly use two `-p` flags

cc: Christian Couder <chriscool@tuxfamily.org>
cc: Taylor Blau <me@ttaylorr.com>
cc: Johannes Altmanninger <aclopte@gmail.com>
cc: Ramsay Jones <ramsay@ramsayjones.plus.com>
cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>
cc: Christian Couder <christian.couder@gmail.com>
cc: René Scharfe <l.s.r@web.de>
cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Elijah Newren <newren@gmail.com>
cc: Johannes Sixt <j6t@kdbg.org>
cc: Josh Steadmon <steadmon@google.com>
cc: Emily Shaffer <emilyshaffer@google.com>

### CODE REVIEW

**Comment by newren** [comment]
@dscho: The linux-leaks test failing above suggests a bug with either GitHub or the CI system.

In particular, the version of t1002 in this tree does NOT contain the "TEST_PASSES_SANITIZE_LEAK=true" line, so no leak checking on that testcase should be done.  Further, digging through the output of the linux-leaks job from the link, I see "CI_COMMIT=18c2598672579f4d58e2455b3c1f43f22d461ffe"; that commit doesn't exist in my history and:

```
$ git ls-remote gitgitgadget | grep 18c2598672579f4d58e2455b3c1f43f22d461ffe
18c2598672579f4d58e2455b3c1f43f22d461ffe	refs/pull/1122/merge
```

Now 1122 is this PR, but what is it merging this PR against?  The PR target is gitgitgadget:temporary/base-in-core-merge-tree, which ALSO does not contain the "TEST_PASSES_SANITIZE_LEAK=true" line.

There was some pretty extreme GitHub slowness yesterday (it was taking hours of delay before jobs would move from queued to running), so I'm wondering if there was just some wonkiness.  But I can't really debug further from this end.  Any ideas?

**Comment by newren** [comment]
Anyway, since the linux-leaks is clearly a mistaken failure...

**Comment by newren** [comment]
Anyway, since the linux-leaks is clearly a mistaken failure...

**Comment by dscho** [comment]
The `/merge` ref is a generated merge commit, you can fetch it to see the commit topology. You can even fetch by SHA if it is unreachable from the current `/merge`...

I plan on looking at this in a bit.

**Comment by dscho** [comment]
Hmm. https://github.com/gitgitgadget/git/runs/4992496825?check_suite_focus=true fails in the same way, and [it _does_ check out the tip of your branch](https://github.com/gitgitgadget/git/runs/4992496825?check_suite_focus=true#step:2:481).

So I tried to reproduce locally, but when I compile with `SANITIZE=leak`, my Git executable segfaults immediately.

**Comment by dscho** [comment]
I now commented out the body of the `restore_sigpipe_to_default()` function (which triggered the segmentation fault), and was able to reproduce. I've bisected it to the patch I myself suggested: 6fb4f4580a581b2e43bc4b8deaa3d2d2bf4a8756

**Comment by dscho** [comment]
And this diff seems to "fix" it:

```diff
diff --git a/diff.c b/diff.c
index 6952035046f..25255ef811a 100644
--- a/diff.c
+++ b/diff.c
@@ -6380,22 +6380,15 @@ N_("you may want to set your %s variable to at least "
 void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc,
 			    FILE *out)
 {
-	const char *fmt = NULL;
-
+	fflush(stdout);
 	if (degraded_cc)
-		fmt = _(degrade_cc_to_c_warning);
+		warning(_(degrade_cc_to_c_warning));
 	else if (needed)
-		fmt = _(rename_limit_warning);
+		warning(_(rename_limit_warning));
 	else
 		return;
 	if (0 < needed)
-		fmt = _(rename_limit_advice);
-
-	fflush(out);
-	if (out == stdout)
-		warning(fmt, varname, needed);
-	else
-		fprintf(out, fmt, varname, needed);
+		warning(_(rename_limit_advice), varname, needed);
 }
 
 static void create_filepairs_for_header_only_notifications(struct diff_options *o)
```

It does not seem to make any sense...

**Comment by dscho** [comment]
I think I've figured it out. _Somehow_ ASAN was _real_ unhappy with me passing a format to `warning()` that does not take any parameters, yet still passing two parameters.

And while I was looking at the code, I saw two more problems with my patch:
- it assumes that the default `out` should be `stdout`, but that's not the case, the default should be `stderr` (and therefore, the `fflush(stdout)` should actually be left untouched)
- my patch mistakenly suppressed the first warning when `0 < needed`, it was an oversight on my part that the function can produce _two_ warnings, not just one.

So with this as a replacement for my original suggestion, not only do things work again, ASAN is also happy:

```diff
diff --git a/diff.c b/diff.c
index 1bfb01c18ec..c6603d3590a 100644
--- a/diff.c
+++ b/diff.c
@@ -6377,17 +6377,30 @@ static const char rename_limit_advice[] =
 N_("you may want to set your %s variable to at least "
    "%d and retry the command.");
 
-void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc)
+void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc,
+			    FILE *out)
 {
 	fflush(stdout);
-	if (degraded_cc)
-		warning(_(degrade_cc_to_c_warning));
-	else if (needed)
-		warning(_(rename_limit_warning));
-	else
+	if (degraded_cc) {
+		if (out == stderr)
+			warning(_(degrade_cc_to_c_warning));
+		else
+			fprintf_ln(out, _(degrade_cc_to_c_warning));
+	} else if (needed) {
+		if (out == stderr)
+			warning(_(rename_limit_warning));
+		else
+			fprintf_ln(out, _(rename_limit_warning));
+	} else
 		return;
-	if (0 < needed)
-		warning(_(rename_limit_advice), varname, needed);
+
+
+	if (0 < needed) {
+		if (out == stdout)
+			warning(_(rename_limit_advice), varname, needed);
+		else
+			fprintf(out, _(rename_limit_advice), varname, needed);
+	}
 }
 
 static void create_filepairs_for_header_only_notifications(struct diff_options *o)
@@ -6870,7 +6883,7 @@ int diff_result_code(struct diff_options *opt, int status)
 
 	diff_warn_rename_limit("diff.renameLimit",
 			       opt->needed_rename_limit,
-			       opt->degraded_cc_to_c);
+			       opt->degraded_cc_to_c, stderr);
 	if (!opt->flags.exit_with_status &&
 	    !(opt->output_format & DIFF_FORMAT_CHECKDIFF))
 		return status;
diff --git a/diff.h b/diff.h
index ce9e2cf2e4f..40c5b78fb0a 100644
--- a/diff.h
+++ b/diff.h
@@ -597,7 +597,8 @@ void diffcore_fix_diff_index(void);
 int diff_queue_is_empty(struct diff_options *o);
 void diff_flush(struct diff_options*);
 void diff_free(struct diff_options*);
-void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc);
+void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc,
+			    FILE *out);
 
 /* diff-raw status letters */
 #define DIFF_STATUS_ADDED		'A'
diff --git a/merge-ort.c b/merge-ort.c
index 9bf15a01db8..46e72b62880 100644
--- a/merge-ort.c
+++ b/merge-ort.c
@@ -4305,7 +4305,7 @@ void merge_switch_to_result(struct merge_options *opt,
 
 		/* Also include needed rename limit adjustment now */
 		diff_warn_rename_limit("merge.renamelimit",
-				       opti->renames.needed_limit, 0);
+				       opti->renames.needed_limit, 0, stderr);
 
 		trace2_region_leave("merge", "display messages", opt->repo);
 	}
diff --git a/merge-recursive.c b/merge-recursive.c
index 9ec1e6d043a..01ca82773cc 100644
--- a/merge-recursive.c
+++ b/merge-recursive.c
@@ -3738,7 +3738,8 @@ static void merge_finalize(struct merge_options *opt)
 		strbuf_release(&opt->obuf);
 	if (show(opt, 2))
 		diff_warn_rename_limit("merge.renamelimit",
-				       opt->priv->needed_rename_limit, 0);
+				       opt->priv->needed_rename_limit, 0,
+				       stderr);
 	FREE_AND_NULL(opt->priv);
 }
 
```

This patch is now quite ugly because of the three repeated `if (out == stderr)` patterns. So maybe better something like this?

```diff
diff --git a/diff.c b/diff.c
index 1bfb01c18ec..b0fe0bd1e93 100644
--- a/diff.c
+++ b/diff.c
@@ -6377,17 +6377,34 @@ static const char rename_limit_advice[] =
 N_("you may want to set your %s variable to at least "
    "%d and retry the command.");
 
-void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc)
+static void warningf(FILE *out, const char *warn, ...)
+{
+	va_list params;
+
+	va_start(params, warn);
+	if (out == stderr)
+		get_warn_routine()(warn, params);
+	else {
+		vfprintf(out, warn, params);
+		fputc('\n', out);
+	}
+	va_end(params);
+}
+
+void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc,
+			    FILE *out)
 {
 	fflush(stdout);
 	if (degraded_cc)
-		warning(_(degrade_cc_to_c_warning));
+		warningf(out, _(degrade_cc_to_c_warning));
 	else if (needed)
-		warning(_(rename_limit_warning));
+		warningf(out, _(rename_limit_warning));
 	else
 		return;
+
+
 	if (0 < needed)
-		warning(_(rename_limit_advice), varname, needed);
+		warningf(out, _(rename_limit_advice), varname, needed);
 }
 
 static void create_filepairs_for_header_only_notifications(struct diff_options *o)
@@ -6870,7 +6887,7 @@ int diff_result_code(struct diff_options *opt, int status)
 
 	diff_warn_rename_limit("diff.renameLimit",
 			       opt->needed_rename_limit,
-			       opt->degraded_cc_to_c);
+			       opt->degraded_cc_to_c, stderr);
 	if (!opt->flags.exit_with_status &&
 	    !(opt->output_format & DIFF_FORMAT_CHECKDIFF))
 		return status;
diff --git a/diff.h b/diff.h
index ce9e2cf2e4f..40c5b78fb0a 100644
--- a/diff.h
+++ b/diff.h
@@ -597,7 +597,8 @@ void diffcore_fix_diff_index(void);
 int diff_queue_is_empty(struct diff_options *o);
 void diff_flush(struct diff_options*);
 void diff_free(struct diff_options*);
-void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc);
+void diff_warn_rename_limit(const char *varname, int needed, int degraded_cc,
+			    FILE *out);
 
 /* diff-raw status letters */
 #define DIFF_STATUS_ADDED		'A'
diff --git a/merge-ort.c b/merge-ort.c
index 9bf15a01db8..46e72b62880 100644
--- a/merge-ort.c
+++ b/merge-ort.c
@@ -4305,7 +4305,7 @@ void merge_switch_to_result(struct merge_options *opt,
 
 		/* Also include needed rename limit adjustment now */
 		diff_warn_rename_limit("merge.renamelimit",
-				       opti->renames.needed_limit, 0);
+				       opti->renames.needed_limit, 0, stderr);
 
 		trace2_region_leave("merge", "display messages", opt->repo);
 	}
diff --git a/merge-recursive.c b/merge-recursive.c
index 9ec1e6d043a..01ca82773cc 100644
--- a/merge-recursive.c
+++ b/merge-recursive.c
@@ -3738,7 +3738,8 @@ static void merge_finalize(struct merge_options *opt)
 		strbuf_release(&opt->obuf);
 	if (show(opt, 2))
 		diff_warn_rename_limit("merge.renamelimit",
-				       opt->priv->needed_rename_limit, 0);
+				       opt->priv->needed_rename_limit, 0,
+				       stderr);
 	FREE_AND_NULL(opt->priv);
 }
 
```

Better, but it'd probably be even better to move the `warningf()` function into `usage.c` so that it can use the `warn_routine` directly, without calling `get_warn_routine()`...

**Comment by newren** [comment]
Thanks for digging.  I still think it's kind of weird though: diff_warn_rename_limit() didn't show up in _any_ of the stack traces I looked at from the build results, so I didn't even suspect it.  Also, I'm still stumped by this side:

```
$ git fetch gitgitgadget refs/pull/1122/merge
$ git grep -l TEST_PASSES_SANITIZE_LEAK origin/master | wc -l 
228
$ git grep -l TEST_PASSES_SANITIZE_LEAK FETCH_HEAD | wc -l 
89
$ git grep -l TEST_PASSES_SANITIZE_LEAK FETCH_HEAD | grep t1002
$
```

Why did the test even run if it's not flagged?

**Comment by dscho** [comment]
I'm not quite certain, but I really think that it's a bug in ASAN, where it assumes that the correct number of parameters is passed to a format function, and gets utterly confused otherwise, flagging bogus stuff.

As to why the test runs? It's [`t1001`](https://github.com/gitgitgadget/git/runs/4992496825?check_suite_focus=true#step:4:1644), not `t1002`, and the former [_is_ marked as passing the leak checks](https://github.com/gitgitgadget/git/blob/e7c63425a0e4070a3bfd0e7614d7447a42e3d598/t/t1001-read-tree-m-2way.sh#L24).

**Comment by newren** [comment]
> I'm not quite certain, but I really think that it's a bug in ASAN, where it assumes that the correct number of parameters is passed to a format function, and gets utterly confused otherwise, flagging bogus stuff.
> 
> As to why the test runs? It's [`t1001`](https://github.com/gitgitgadget/git/runs/4992496825?check_suite_focus=true#step:4:1644), not `t1002`, and the former [_is_ marked as passing the leak checks](https://github.com/gitgitgadget/git/blob/e7c63425a0e4070a3bfd0e7614d7447a42e3d598/t/t1001-read-tree-m-2way.sh#L24).

Ah, so I can't read.  Sorry about that.

**Comment by dscho** [comment]
> Ah, so I can't read.

😆 

FWIW I just pushed a cleaned-up version of my patch: https://github.com/dscho/git/compare/adf0020f201%5E%5E...adf0020f201

**Comment by dscho** [comment]
> FWIW I just pushed a cleaned-up version of my patch: [dscho/git@adf0020f201^^...adf0020](https://github.com/dscho/git/compare/adf0020f201%5E%5E...adf0020f201)

CI build is running here: https://github.com/dscho/git/runs/4995727177?check_suite_focus=true

**Comment by dscho** [comment]
> CI build is running here: https://github.com/dscho/git/runs/4995727177?check_suite_focus=true

... and the `linux-leaks` job passed. Good.

Now, can I ask for a favor? I would love for the `merge-tree` command to accept `-z`, to terminate the conflict entries (and probably even the messages) with NUL instead of LF (and to avoid shell-quoting the paths)...

**Comment by newren** [comment]
> > CI build is running here: https://github.com/dscho/git/runs/4995727177?check_suite_focus=true
> 
> ... and the `linux-leaks` job passed. Good.

Awesome, thanks.

> Now, can I ask for a favor? I would love for the `merge-tree` command to accept `-z`, to terminate the conflict entries (and probably even the messages) with NUL instead of LF (and to avoid shell-quoting the paths)...

Sure!

**Pull request closed without merging**
