### PR TITLE
git-show-ref.txt: fix order of flags

### PR DESCRIPTION
**Pull request by newren**
A trivial documentation fix...and testing out gitgitgadget.  :-)

### CODE REVIEW

**Comment by dscho** [comment]
@newren sorry about that. I have a ticket open to address this unpleasant surprise for first-time users of GitGitGadget: https://github.com/gitgitgadget/gitgitgadget/issues/52

**Comment by newren** [comment]
@dscho: No worries; you warned me in IRC that I'd need to contact you to get permission.  It just took me longer than I expected before I tried it out and when I did I temporarily forgot that step.  Anyway, thanks for the access.

**Pull request closed without merging**
