### PR TITLE
checkout/reset/read-tree: fix --recurse-submodules in linked worktree

### PR DESCRIPTION
**Pull request by phil-blain**
Changes since v1:
- revert the addition of a dash in "file1 updated" by correctly using the 'tag' argument of test_commit
- improve the commit message for the 3rd patch, as suggested by Eric
- fix spacing when redirecting into 'expect' and 'actual'
- harden the tests by echoing expected values into expect, as suggested by Stolee
  (I did that in both tests)
- remove test_might_fail and use test_expect_code
- add the 'git log' test suggested by Stolee

v1:
This series fixes the behaviour of `git checkout/reset/read-tree --recurse-submodules` when they are called in a linked worktree (created by `git worktree add`). 

Although submodules are cloned in `$GIT_COMMON_DIR/worktrees/<name>/modules` upon issuing `git submodule update` in the linked worktree, any invocation of `git checkout/reset/read-tree --recurse-submodules` that changes the state of the submodule(s) will incorrectly operate on the repositories of the submodules in the main worktree, i.e. the ones at `$GIT_COMMON_DIR/modules/`. 

The fourth patch fixes this behaviour by using `get_git_dir()` instead of `git_common_dir()` in `submodule.c::submodule_move_head` and `submodule.c::submodule_unset_core_worktree` to construct the path to the submodule repository.

The first 3 patches are clean-up patches on t7410-submodule-checkout-to.sh (renamed to t2405-worktree-submodule.sh) to bring it up to date.

Cc:Max Kirillov <max@max630.net> Brandon Williams <bwilliams.eng@gmail.com> Jonathan Tan <jonathantanmy@google.com> Stefan Beller <stefanbeller@gmail.com> Nguyễn Thái Ngọc Duy <pclouds@gmail.com> Eric Sunshine <sunshine@sunshineco.com> Derrick Stolee <stolee@gmail.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
@dscho sorry to bother you, it seems neither v1 nor v2 of this PR was sent with the CC's I added in the footer of the PR description... is it because there is no space between "Cc:" and the first name ?

What syntax is accepted for the emails in the CC footer ? I see you and Stolee seem to use Markdown with mailto links, is this essential ? I usually copy the contact from Mail on my Mac which when pasted looks like `Brandon Williams <bwilliams.eng@gmail.com>`...

**Comment by dscho** [comment]
> is it because there is no space between "Cc:" and the first name ?

I _think_ so.

> I see you and Stolee seem to use Markdown with mailto links, is this essential ?

No, the GitHub renderer makes them look like it, but we really write the `Cc:` lines the same way as we would in the commit message.

> Also regarding list etiquette, what should I do now ? should I /submit again with the CC's fixed ? will this send a v3 or GGG will realize that nothing has changed and re-send v2 ?

I would simply reply to the cover letter manually, with all those Cc:s. GitGitGadget would refuse to send a v3 because nothing changed...

**Comment by dscho** [comment]
> > is it because there is no space between "Cc:" and the first name ?
> 
> I _think_ so.

Yep, it would appear your hunch was right: https://github.com/gitgitgadget/gitgitgadget/blob/f9f7cc94bd3e20e5e9217233c0abfed6b5b091ac/lib/patch-series.ts#L296

Maybe you want to patch this, substituting the space in the regular expression by `\s*`, then add or modify a test and open a PR?

**Comment by phil-blain** [comment]
Thanks a lot for checking! I’ll gladly look into patching that :)

**Pull request closed without merging**
