### PR TITLE
[GSoC][PATCH] Applicant Microproject - Modernizing t4202

### PR DESCRIPTION
**Pull request by JackMcGu**
Hi, My name is Jack McGuinness, and a while ago I expressed my interest in git and GSoC. However, due to some personal and academic reasons I haven't been able to work on my micro project  since then. I was able to work on my proposal, and I will be finished with it before the submission deadline, but I just want to express my apologies for doing this so late.

In my patch, I completed the first four bullet points described in https://lore.kernel.org/git/CAPig+cQpUu2UO-+jWn1nTaDykWnxwuEitzVB7PnW2SS_b7V8Hg@mail.gmail.com/ . I will complete the rest of them for t4202 over the rest of today, and submit their respective patches promptly. 

It has taken a few tries to get submitting my patch wrong due to a plethora of problems, but I think this time it will work. 

Thanks for your time,
Jack.

cc: Derrick Stolee <derrickstolee@github.com>

### CODE REVIEW

**Comment by harry-hov** [comment]
Just noticed you closed #1217 and opened this duplicate. You don’t necessarily need to do that. Maybe consider force pushing next time.

**Comment by JackMcGu** [comment]
Thank you for the suggestion! unfortunately, the reason I created a duplicate was because I forgot a blank line between the subject and body in my commit message, and I wanted to stick to the standard.

**Comment by harry-hov** [comment]
> [...] I forgot a blank line between the subject and body in my commit message [...]

Still no need to create duplicate PR

```
git commit --amend
git push -f
```

would do the trick

**Comment by JackMcGu** [comment]
Ok, I didn't know that you could do that. Thank you for letting me know, I'll be sure to remember it next time I mess up!

**Pull request closed without merging**
