### PR TITLE
rebase -i: fix ORIG_HEAD handling

### PR DESCRIPTION
**Pull request by phillipwood**
The buffer containing the oid for ORIG_HEAD is overwritten before ORIG_HEAD is created. This series fixes that bug and then converts the code to use struct object_id rather than passing around strings.

Thanks to Caspar for reporting the bug and providing a reproducible example

Changes since v1:
* Updated the commit message to patch 1 as suggested by Junio
* Moved the conversion from find_unique_abbrev() to oid_to_hex() from patch 1 to patch 4
* Fixed a compilation error in patch 3 (the required change was in patch 4 by a mistake)

Cc: Johannes Schindelin <Johannes.Schindelin@gmx.de>, Caspar Duregger <herr.kaste@gmail.com>

cc: Phillip Wood <phillip.wood123@gmail.com>

### CODE REVIEW

**Review by dscho — APPROVED** [review]
At the moment, I cannot send a mail to the mailing list, so I'll just send a "Well Done" via GitHub.

**Comment by phillipwood** [comment]
Thanks @dscho

**Pull request closed without merging**
