### PR TITLE
contrib: Add --recursive flag for bash completion

### PR DESCRIPTION
**Pull request by purpleidea**
This flag was missing from the list, and I use it quite often :)

Signed-off-by: James Shubin <james@shubin.ca>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by nasamuffin** [comment]
Before you submit, I encourage you to take a second look at your commit message; the one you have now will probably get nitpicked on the mailing list. Instead, you will probably be asked to write a commit message explaining the effects/reasoning of your change which isn't clear from the diff. Take a look at some of the other commit messages in the project (excepting the merge commits) for examples :)

**Comment by dscho** [comment]
> Before you submit, I encourage you to take a second look at your commit message; the one you have now will probably get nitpicked on the mailing list.

It would make sense to listen to @nasamuffin.

**Comment by purpleidea** [comment]
@dscho I asked @nasamuffin about how to improve on IRC and they didn't have an answer. Patch seems to have already been integrated.

And as for the way the patch got sent to list-- that wasn't me, that was all GGG. If you look at my original commit, it is quite clean.

**Comment by nasamuffin** [comment]
@purpleidea I didn't have an answer because I had gone home for the day and wasn't reading IRC.

As for the GGG formatting, can you let us know how the documentation could be clearer to explain that the PR description at the top of the Conversation tab is what's sent as the cover letter to the list?

**Comment by purpleidea** [comment]
It's my first time using gggwhatever, and honestly, it's been a pretty terrible experience so far. Just a bunch of incoherent notifications... See above. Oh well. `<unsubscribe>`.

**Comment by dscho** [comment]
> It's my first time using gggwhatever, and honestly, it's been a pretty terrible experience so far

@purpleidea So you're in a unique position to help improve it.

The idea is that GitGitGadget will keep you updated about the progress of your patch, and the progress is not a PR flow. The progress is that your patch will be published as a branch at https://github.com/gitster/git, this branch will be merged at least once into `pu`, which is a meta branch that is rewritten all the time. Whenever changes are required, you are expected to "re-roll", i.e. to amend, force-push and `/submit` again. These patch iterations should then get picked up and the branch at https://github.com/gitster/git will get updated, and the next update to `pu` should include it. Once your patch stabilizes, it will be integrated into the `next` branch. That branch is only rewritten short after a new major release, and it is expected that the integrated patches will "cook" for a while, i.e. be tested, and if any changes are required, you are expected to provide them as add-on patches (e.g. when your patch causes crashes). These add-on patches will usually make it into `next` pretty quickly. Once the dust has settled in `next`, your patch will be integrated into `master` (and/or `maint`). At that stage, it is on route into the next major Git version (or bugfix release).

@purpleidea Now that you know all this, maybe you can undo the damage of your comment that _caused_ a lousy start into the week, and help make GitGitGadget do what you would have liked it to do instead. Suggestions? What changes would make for a better experience?

**Comment by purpleidea** [comment]
@dscho 

> @purpleidea Now that you know all this, maybe you can undo the damage of your comment that caused a lousy start into the week

I'm not interested in you making me feel guilty about a one-line patch. I'm trying to get you to have a look at the above history and see that it's incredibly noisy, and unhelpful for anyone new to git core. Nobody knows what "pu" is, and the message "This patch series was integrated" is not clear, especially when it happens seven times.

@dscho Please don't ping me anymore. Thanks!

**Comment by dscho** [comment]
> I'm not interested in you making me feel guilty about a one-line patch.

I don't make you feel guilty, I pointed out a poor way of communicating. It's not like anybody asked you to scoff at GitGitGadget which, while it is not ideal, has been a ton of work. Yeah, yeah, I know, you're not interested in having that pointed out to you, so now you can go and feel great about your one-line patch.

**Comment by dscho** [comment]
I guess it is my fault. I should have refrained from [encouraging the contributor](https://github.com/git/git/pull/667#issuecomment-551957170), after [the](https://github.com/git/git/pull/667#issue-338725916) initial [impressions](https://github.com/git/git/pull/667#issuecomment-551870637) were [not](https://github.com/git/git/pull/667#issuecomment-551888322) that [great](https://github.com/gitgitgadget/git/pull/461#issue-340151149) (ignoring [nasamuffin's suggestion](https://github.com/gitgitgadget/git/pull/461#issuecomment-553184736), thereby forcing [the Git maintainer to pick up the slack](https://public-inbox.org/git/xmqqlfskbfru.fsf@gitster-ct.c.googlers.com)).

This is a valuable lesson to me.

**Pull request closed without merging**
