### PR TITLE
[GSOC] cat-file: reuse ref-filter logic

### PR DESCRIPTION
**Pull request by adlternative**
This patch series make cat-file reuse ref-filter logic.

Change from last version:
1. Declare `buf_size` in `if (atom_type == ATOM_RAW)` block.
2. Modify the code style of the test.
3. Delete "use_textconv" and "use_filter" flag. Instead, add 
member `cat_file_cmdmode` to struct `ref_array_item`.
4.  Add function reject_atom() to enhance the readability of the code.
5. Use a "fast path" to output object data to reduce the performance
degradation of `cat-file --batch` with the suggest of Ævar Arnfjörð Bjarmason.

Due to the changes to the "seen" branch, it seems that this branch cannot be
merged with "seen" normally.

cc: Junio C Hamano gitster@pobox.com
cc: Christian Couder christian.couder@gmail.com
cc: Hariom Verma hariom18599@gmail.com
cc: Bagas Sanjaya bagasdotme@gmail.com
cc: Jeff King peff@peff.net
cc: Ævar Arnfjörð Bjarmason avarab@gmail.com
cc: Eric Sunshine <sunshine@sunshineco.com>

### CODE REVIEW

**Comment by adlternative** [comment]
@dscho 
I am a little confused that where should I rebase this patch to? 
Junio said I need to resolve the conflict between this branch and the "seen" branch, so
my patch must base on zh/cat-file-batch-fix, I choice (bb9a3a8f77 Merge branch 'zh/cat-file-batch-fix' into jch) 
as the base commit. But github only allow me to base the patch on a branch but not the a normal commit.
So here are some "Merge" commits appear. 

If I go back the last time I send the patch, I would rebase it on "seen".
But at the same time, Junio fix a my bug in  (03de5e28 "BANDAID: sparse fixes"), "seen" has changed.

So what should I do now?

**Comment by dscho** [comment]
> I am a little confused that where should I rebase this patch to?

The problem was that you targeted `seen`, and it changes _real_ fast.

Better try to target another of the available branches (I usually look through the merge commits in `seen` to figure out which one).

**Comment by dscho** [comment]
> my patch must base on zh/cat-file-batch-fix and zh/ref-filter-atom-type, I choice
> ([bb9a3a8](https://github.com/gitgitgadget/git/commit/bb9a3a8f77e13b7a414cf64bf294c3f59f2444c9) Merge branch 'zh/cat-file-batch-fix' into jch) as the base commit.

Probably a better commit to base it on would be `bb9a3a8^2`, i.e. https://github.com/gitgitgadget/git/commit/ee02ac616435cb1da1e02c8b9c220649d3cec40a, which is the tip of the [`cat-file-batch-fix` branch](https://github.com/gitgitgadget/git/compare/zh/cat-file-batch-fix).

**Comment by adlternative** [comment]
> > my patch must base on zh/cat-file-batch-fix and zh/ref-filter-atom-type, I choice
> > ([bb9a3a8](https://github.com/gitgitgadget/git/commit/bb9a3a8f77e13b7a414cf64bf294c3f59f2444c9) Merge branch 'zh/cat-file-batch-fix' into jch) as the base commit.
> 
> Probably a better commit to base it on would be `bb9a3a8^2`, i.e. [ee02ac6](https://github.com/gitgitgadget/git/commit/ee02ac616435cb1da1e02c8b9c220649d3cec40a), which is the tip of the [`cat-file-batch-fix` branch](https://github.com/gitgitgadget/git/compare/zh/cat-file-batch-fix).

Sorry, but ee02ac6 don't own zh/ref-filter-atom-type contents, this is why I thought it was difficult to solve before.
Fortunately, zh/ref-filter-atom-type  already merged into master. So I tried to cherry-pick zh/cat-file-batch-fix to master,
and rebase this new patch cat-file-batch-refactor-rebase-version onto it. It's work! See https://github.com/gitgitgadget/git/pull/993

Thanks!

**Comment by dscho** [comment]
@adlternative okay! For the record, you can easily re-target PRs to different branches. That way, you don't break the v1, v2, v3, ... numbering.

**Pull request closed without merging**
