### PR TITLE
RFC: Remove the present-despite-SKIP_WORKTREE class of bugs

### PR DESCRIPTION
**Pull request by newren**
(Maintainer note: This series builds on vd/sparse-clean-etc, because it tweaks one of the testcases added there.)

Files in the present-despite-SKIP_WORKTREE state have caused no ends of discussions and bugs[1,2,3,4,5,6,...and lots of others].  Trying to address the big issue of discovering & recovering from this state has befuddled me for over a year because I was worried we'd need additional code at every skip_worktree-checking path in the code (and they are all over the place), and that we'd make the code significantly slower unless we plumbed a bunch of additional information all over the place to allow some reasonable optimizations.

This series tries to solve the problem a bit differently by automatic early discovery and recovery; as it result, it greatly simplifies the landscape, reduces our testing matrix burden, and fixes a large swath of bugs.  It does have a cost, though.  See the commit message of patch 3 (the crux of this series) for the details.

Quick overview:
  * Patches 1 & 2 add a test to demonstrate accidental deletion of possibly-modified files, and then fix the bug.
  * Patch 3 is the crux of this series; a small amount of code with a huge commit message
  * Patch 4 updates the documentation
  * Patch 5 adds some optimizations to reduce the performance impact of patch 3

[1] https://lore.kernel.org/git/CABPp-BFnFpzwGC11TLoLs8YK5yiisA5D5-fFjXnJsbESVDwZsA@mail.gmail.com/
[2] https://lore.kernel.org/git/CABPp-BGJ_Nvi5TmgriD9Bh6eNXE2EDq2f8e8QKXAeYG3BxZafA@mail.gmail.com/
[3] https://lore.kernel.org/git/pull.809.git.git.1592356884310.gitgitgadget@gmail.com/
[4] commit 66b209b86a ("merge-ort: implement CE_SKIP_WORKTREE handling with conflicted entries", 2021-03-20)
[5] commit ba359fd507 ("stash: fix stash application in sparse-checkouts", 2020-12-01)
[6] https://lore.kernel.org/git/CABPp-BH9tju7WVm=QZDOvaMDdZbpNXrVWQdN-jmfN8wC6YVhmw@mail.gmail.com/

cc: Victoria Dye <vdye@github.com>
cc: Derrick Stolee <stolee@gmail.com>
cc: Lessley Dennington <lessleydennington@gmail.com>

### CODE REVIEW

**Comment by newren** [comment]
@dscho : I don't want to insert newlines into long mailing list URLs; that would break them.  Is there some way to override gitgitgadget or tell it to only complain about line-wrapping if there line contains spaces/tabs after the 10th column or so (sometimes I have lists, so I do have a few spaces at the beginning of the line, but it's pretty much just >80 character URLs).

**Comment by dscho** [comment]
> Is there some way to override gitgitgadget or tell it to only complain about line-wrapping if there line contains spaces/tabs after the 10th column or so (sometimes I have lists, so I do have a few spaces at the beginning of the line, but it's pretty much just >80 character URLs).

Sure, it's just code :-)

In this instance, probably we need to insert something like ` && !this.lines[i].slice(10).match(/\s/)` into https://github.com/gitgitgadget/gitgitgadget/blob/21d271a356dce0e076420ab34a35d7f0ffa100b6/lib/commit-lint.ts#L113

Maybe even leave out the `slice(10)`, i.e. require the entire line to be whitespace-free if it wants to be overly long?

> (I fell back to `git send-email` for now, so I'm just curious for the future.)

Fair enough. Please note that I _can_ reconstruct the data manually, to allow subsequent iterations to be sent via GitGitGadget again, but it's laborious. When I have some time (*cough, cough*) I want to make this easier.

**Comment by dscho** [comment]
> Maybe even leave out the `slice(10)`, i.e. require the entire line to be whitespace-free if it wants to be overly long?

Ah, I see... you want lines of this form to be allowed:

```
[2] https://lore.kernel.org/git/CABPp-BH9tju7WVm=QZDOvaMDdZbpNXrVWQdN-jmfN8wC6YVhmw@mail.gmail.com/
```

**Comment by dscho** [comment]
> > Is there some way to override gitgitgadget or tell it to only complain about line-wrapping if there line contains spaces/tabs after the 10th column or so (sometimes I have lists, so I do have a few spaces at the beginning of the line, but it's pretty much just >80 character URLs).
> 
> Sure, it's just code :-)

Here is the PR: https://github.com/gitgitgadget/gitgitgadget/pull/842

**Comment by webstech** [comment]
> Here is the PR: [gitgitgadget/gitgitgadget#842](https://github.com/gitgitgadget/gitgitgadget/pull/842)

Now merged.

**Comment by newren** [comment]
I was forced to replace this with #1114, so that I could change the PR base.

**Pull request closed without merging**
