### PR TITLE
Fixed typo in 'git rm "paht"' to 'git rm "path"'

### PR DESCRIPTION
**Pull request by nirgeier**
Signed-off-by: Nir Geier <nirgeier@gmail.com>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
@nirgeier you probably passed the commit message via `commit -m`? I say that because this is the current commit message:

> Fixed typo in 'git rm ""' to 'git rm ""' 

As you can see, the `$paht` and `$path` parts were lost 😄

**Comment by newren** [comment]
This is not a good change; the typo was intentional and used as an example of what happens when someone mistypes a command.  If you fix the typo, the paragraph in the release notes no longer makes sense.

**Comment by dscho** [comment]
Whoops, you're right, @newren! I totally overlooked this.

@nirgeier I'm going to close this, given that argument against this patch.

**Pull request closed without merging**
