### PR TITLE
merge-tree: batched merges

### PR DESCRIPTION
**Pull request by newren**
When a branch is updated, a Git hosting provider may want to check all open code reviews targetting the given branch to determine if those code reviews can still merge cleanly into the target branch.  Provide a new --stdin option to git-merge-tree to enable this capability, with each line of input providing the branches for the next merge.

Note: this still requires all the merges to be in the same repository.  There is some code I noticed a while back in merge-ort that implicitly uses the_repository (indirectly), and there may be more uses that I am unaware of.

### CODE REVIEW

**Comment by newren** [comment]
@dscho: Your colleague, Carl (IIRC), suggested this idea and asked about it the final day of Git Merge.  I didn't get his last name, and I may have mis-remembered his first name, so I have no way to tag him on this changes.  But I thought it sounded relatively easy and that it might provide significant savings, so I thought I'd take a stab at it.  I don't know if we want to output the exit status in some other order, or whether I got the right number of NUL characters to make sure you can tell where one merge ends and the next starts.  (I'm also a little unclear on whether your colleague wanted to take a stab at this patch; if so, maybe we should just ignore my patch and let him give it a shot?)

**Comment by dscho** [comment]
Thank you so much for doing this! Yes, @brasic asked for this.

As it happens, I implemented an alternative for this ;-)

```diff
From bbe97096b5034c6afa5543977ae22bcccead4e88 Mon Sep 17 00:00:00 2001
From: Johannes Schindelin <johannes.schindelin@gmx.de>
Date: Mon, 19 Sep 2022 17:05:54 +0200
Subject: [PATCH] merge-tree: introduce a batch mode

One common use case for running `merge-tree` is to see whether any of a
bunch of PRs has conflicts after their base branch was updated.

With this new mode, `git merge-tree` supports that user case better by
accepting one revision (the "head branch") via the command-line and then
a list of revisions via `stdin` (the "merge heads"), performing the
respective merges and printing their outputs separated by an empty line
(or a `NUL` if running with `-z`).

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>
---
 Documentation/git-merge-tree.txt |  6 ++++++
 builtin/merge-tree.c             | 36 ++++++++++++++++++++++++++++++++
 t/t4301-merge-tree-write-tree.sh | 29 +++++++++++++++++++++++++
 3 files changed, 71 insertions(+)

diff --git a/Documentation/git-merge-tree.txt b/Documentation/git-merge-tree.txt
index ed91107bf0..80322a1d74 100644
--- a/Documentation/git-merge-tree.txt
+++ b/Documentation/git-merge-tree.txt
@@ -83,6 +83,12 @@ OPTIONS
 	print out the tree OID of `<branch1>` and exit with the specified
 	code to indicate this specific situation.
 
+--batch-merge-heads-via-stdin::
+	Accept `<branch1>` as command-line argument, and then a series of
+	`<branch2>` via `stdin`. The command will then behave as if it had
+	been called with `<branch1>` and each `<branch2>`, printing an empty
+	line (or `NUL` if `-z` was specified, too) after each merge output.
+
 [[OUTPUT]]
 OUTPUT
 ------
diff --git a/builtin/merge-tree.c b/builtin/merge-tree.c
index 5020d390a7..fb1ed055d8 100644
--- a/builtin/merge-tree.c
+++ b/builtin/merge-tree.c
@@ -564,10 +564,12 @@ int cmd_merge_tree(int argc, const char **argv, const char *prefix)
 	const char * const merge_tree_usage[] = {
 		N_("git merge-tree [--write-tree] [<options>] <branch1> <branch2>"),
 		N_("git merge-tree [--trivial-merge] <base-tree> <branch1> <branch2>"),
+		N_("git merge-tree --batch-merge-heads-via-stdin [<options>] <branch1> < <branches>"),
 		NULL
 	};
 	int resolve_via_stdin = 0;
 	struct strmap resolve_conflicts = STRMAP_INIT;
+	int batch_merge_heads_via_stdin = 0;
 	struct option mt_options[] = {
 		OPT_CMDMODE(0, "write-tree", &o.mode,
 			    N_("do a real merge instead of a trivial merge"),
@@ -597,6 +599,9 @@ int cmd_merge_tree(int argc, const char **argv, const char *prefix)
 		OPT_INTEGER(0, "exit-with-status-if-already-merged",
 			    &o.exit_with_status_if_already_merged,
 			    N_("exit code to use if already merged")),
+		OPT_BOOL(0, "batch-merge-heads-via-stdin",
+			 &batch_merge_heads_via_stdin,
+			 N_("perform multiple merges")),
 		OPT_END()
 	};
 
@@ -604,6 +609,37 @@ int cmd_merge_tree(int argc, const char **argv, const char *prefix)
 	original_argc = argc - 1; /* ignoring argv[0] */
 	argc = parse_options(argc, argv, prefix, mt_options,
 			     merge_tree_usage, PARSE_OPT_STOP_AT_NON_OPTION);
+
+	if (batch_merge_heads_via_stdin) {
+		struct strbuf merge_head = STRBUF_INIT;
+		strbuf_getline_fn getline_fn = line_termination ?
+			strbuf_getline_lf : strbuf_getline_nul;
+		int ret = 0;
+
+		if (resolve_via_stdin)
+			die(_("%s is incompatible with %s"),
+			    "--batch-merge-heads-via-stdin",
+			    "--resolve-via-stdin");
+
+		if (o.mode == MODE_TRIVIAL)
+			die(_("%s is incompatible with %s"),
+			    "--batch-merge-heads-via-stdin",
+			    "--trivial-merge");
+
+		if (argc != 1)
+			usage_msg_opt(_("expect <branch1> as argument, "
+					"all merge heads via `stdin`"),
+				      merge_tree_usage, mt_options);
+
+		while (!getline_fn(&merge_head, stdin)) {
+			if (real_merge(&o, argv[0], merge_head.buf, prefix))
+				ret = 1;
+			fputc(line_termination, stdout);
+		}
+
+		return ret;
+	}
+
 	switch (o.mode) {
 	default:
 		BUG("unexpected command mode %d", o.mode);
diff --git a/t/t4301-merge-tree-write-tree.sh b/t/t4301-merge-tree-write-tree.sh
index 5dccd7d08f..0e822e9322 100755
--- a/t/t4301-merge-tree-write-tree.sh
+++ b/t/t4301-merge-tree-write-tree.sh
@@ -305,4 +305,33 @@ test_expect_success 'respect merge.renames' '
 	git diff $TREE:sequence $TREE:counting
 '
 
+test_expect_success '--batch-merge-heads-via-stdin' '
+	test_write_lines $(git rev-parse side2 side3 tweak1) >merge-heads.txt &&
+	git merge-tree --batch-merge-heads-via-stdin side1^ <merge-heads.txt &&
+	test_must_fail git merge-tree --batch-merge-heads-via-stdin side1 <merge-heads.txt >out &&
+	anonymize_hash out >actual &&
+	q_to_tab >expect <<-\EOF &&
+	HASH
+	100644 HASH 1Qgreeting
+	100644 HASH 2Qgreeting
+	100644 HASH 3Qgreeting
+	100644 HASH 1Qwhatever
+	100644 HASH 2Qwhatever
+
+	Auto-merging greeting
+	CONFLICT (content): Merge conflict in greeting
+	Auto-merging numbers
+	CONFLICT (file/directory): directory in the way of whatever from side1; moving it to whatever~side1 instead.
+	CONFLICT (modify/delete): whatever~side1 deleted in HASH and modified in side1.  Version side1 of whatever~side1 left in tree.
+
+	HASH
+
+
+	HASH
+
+
+	EOF
+	test_cmp expect actual
+'
+
 test_done
-- 
2.38.0.rc0.windows.1
```

We tested this and found that it takes up to 5 minutes to batch-merge 700+ pairs. These are not any random run-of-the-mill merges, they are heavy-duty merges in a busy and large repository. In other words, they are a good use case to optimize for.

I've hence littered the code with Trace2 statements and found a few hot paths in the custom code that I haven't had a chance to upstream yet. But I fear that the most sensible course of action is to use multi-threading to accelerate things, as I have noticed that the CPU isn't really used efficiently (I tried this in a 32-core Codespace).

**Comment by newren** [comment]
> We tested this and found that it takes up to 5 minutes to batch-merge 700+ pairs. These are not any random run-of-the-mill merges, they are heavy-duty merges in a busy and large repository. In other words, they are a good use case to optimize for.
>
> I've hence littered the code with Trace2 statements and found a few hot paths in the custom code that I haven't had a chance to upstream yet. But I fear that the most sensible course of action is to use multi-threading to accelerate things, as I have noticed that the CPU isn't really used efficiently (I tried this in a 32-core Codespace).

One thing to note is that batched merges are meant to optimize away the overhead of separate process invocations.  If the cost of the merge is large relative to process invocation overhead, then you won't gain much from the batched merges optimization (which suggests this optimization would be more helpful at reducing say p50 times than p99 times).

In fact, parallelization may not make that much of a difference either.  If process invocation overhead is relatively small, then forking N merge-tree processes is going to take only a little more effort than having a single merge-tree process run N merges in parallel.

I don't know if the cases you are looking at fall into that category, but it's worth double checking.

There's also another idea here that may or may not be interesting: the fact that my patch series allows the first parent to vary means you could leave a "daemon" process up and running and just throughout the day give it more branches/commits to merge, some of which might not have existed when the program was first invoked.  Granted, there's overhead to leaving up a daemon process for each repository up and running so I don't know if you really want to do that, but maybe there's something clever or interesting that can be done there for repositories used often enough to make it matter?  (Or maybe there's a way to force git to dump and reload the_repository and various config so we could have a global daemon process?)

**Comment by newren** [comment]
Oh, and just to be clear, I'm not saying you should avoid optimizing the heavy-duty merges in your large and busy repository; by all means, go ahead.  I'm just noting there's a possibility this patch series only provides significant benefit for some of the smaller, simpler repositories.

**Pull request closed without merging**
