### PR TITLE
Remove more index compatibility macros

### PR DESCRIPTION
**Pull request by derrickstolee**
UPDATE: this is now based on ag/merge-strategies-in-c to avoid conflicts in 'seen'. The changes in builtin/rm.c still conflict with mt/rm-sparse-checkout, but that branch seems to be waiting for a clearer plan on some corner cases. I thought about ejecting it, but 'rm' still uses ce_match_stat(), so just dropping the patch gives less of a final stake at the end of the series. (I'm still open to it, if necessary.)

I noticed that Duy's project around USE_THE_INDEX_COMPATIBILITY_MACROS has been on pause for a while. Here is my attempt to continue that project a little.

I started going through the builtins that still use `cache_name_pos()` and the first was easy: mv and rm.

Then I hit update-index and it was a bit bigger.

My strategy for update-index was to create static globals "repo" and "istate" that point to the_repository and the_index, respectively. Then, I was able to remove macros one-by-one without changing method prototypes within the file. Then, these static globals were also removed by systematically updating the local method prototypes, plus some fancy structure stuff for the option parsing callbacks.

I had started trying to keep everything local to the method signatures, but I hit a snag when reaching the command-line parsing callbacks, which I could not modify their call signature. At that point, I had something that was already much more complicated than what I present now. Outside of the first update-index commit, everything was a mechanical find/replace.

In total, this allows us to remove four of the compatibility macros because they are no longer used.

Updates in V3
---------------

* Methods that know about the 'repo' pointer no longer also have an 'istate' pointer and instead prefer 'repo->index'

* This includes the callback_data struct which only has a 'repo' member, no 'istate'.

Thanks,
-Stolee

Cc: pclouds@gmail.com
Cc: gitster@pobox.com
cc: Elijah Newren <newren@gmail.com>
cc: Eric Sunshine <sunshine@sunshineco.com>
cc: Alban Gruin <alban.gruin@gmail.com>
cc: Derrick Stolee <stolee@gmail.com>

### CODE REVIEW

**Comment by tacker66** [comment]
Hi Derrick,
could you please /allow me for #831?
Thanks,
Thomas

**Comment by derrickstolee** [comment]
closing to unblock other work.

**Pull request closed without merging**
