### PR TITLE
[QUIMBY] CI run for show-gitdir on top of gitster/es/outside-repo-errmsg-hints

### PR DESCRIPTION
**Pull request by nasamuffin**
This pull request was created by https://github.com/nasamuffin/quimby, a tool for Git contributors who are accustomed to a git-format-patch/git-send-email workflow but want to see the GitGitGadget CI run results. It should probably be ignored!

### CODE REVIEW

**Comment by nasamuffin** [comment]
Hm, the failed tests I can see in the freebsd_12 check are marked "known failure" - is there something else happening there?

**Comment by dscho** [comment]
Could Quimby maybe be a bit more parsimonious with opening new PRs? It could reuse a single PR per user, for example. It's a bit exhausting to get all those notifications for something not intended to be submitted via GitGitGadget...

**Comment by nasamuffin** [comment]
You may have seen some spurious new topics today as I fixed a small bug. I
don't see that in normal use this tool would create any more PRs than a
user with a typical GGG workflow. If I opened one PR per user it would
become difficult for me to test multiple branches simultaneously, which
becomes desirable when the check runtime is longer than an hour or so, and
I imagine it could be difficult to post the result of the test run to the
mailing list.

I'm surprised to hear these PRs are generating notifications for you,
though, since they are all opened in draft mode - which I understood to
mean "limited publicity since it's a draft".

Since you suggested the well-formed subject line, wouldn't it make it easy
to filter mails generated by this tool?

**Comment by dscho** [comment]
I see *all* updates so I can help new contributors before they get frustrated. But I understand your point, and it should be easy enough for me to "swipe left" the Quimby PRs. Sorry for complaining!

**Comment by nasamuffin** [comment]
This successful CI run is from `git commit --amend && git push -f` - it's identical to the patch on list.

**Pull request closed without merging**
