### PR TITLE
bitmap-format.txt: fix some formatting issues and include checksum info

### PR DESCRIPTION
**Pull request by Abhra303**
There are some issues in the bitmap-format html page. For example, some nested lists are shown as top-level lists (e.g. [1]- Here `BITMAP_OPT_FULL_DAG (0x1)` and `BITMAP_OPT_HASH_CACHE (0x4)` are shown as top-level list).  There is also a need of adding info about trailing checksum in the docs.

Changes since v3:
* spaces are used instead of tabs
* fixed remaining `<pre>` blocks

Changes since v2:
The last two commits are updated to address the suggestions. These changes are -
* previously omitted blank lines are re-added. In the updated commit, use of `<pre>` blocks are decreased. Description lists and `+` are used instead to add more than one paragraphs under lists.
Readability of the source text might decrease due to the use of `+`. But other documentation files (e.g. git-add.txt) also use it to connect two paragraphs. So, I hope this is acceptable.

* Information about trailing checksum is updated (as suggested by Taylor)

Changes since v1:
* a new commit addressing bitmap-format.txt html page generation is added
* Remove extra indentation from the previous change
* elaborate more about the trailing checksum (as suggested by Kaartic)

initial version:
* first commit fixes some formatting issues
* information about trailing checksum in the bitmap file is added in the bitmap-format doc.

[1] https://git-scm.com/docs/bitmap-format#_on_disk_format

cc: Taylor Blau me@ttaylorr.com
cc: Kaartic Sivaraam kaartic.sivaraam@gmail.com
cc: Derrick Stolee derrickstolee@github.com
cc: Junio C Hamano gitster@pobox.com

### CODE REVIEW

**Comment by dscho** [comment]
Didn't work. Now I am failing to find the setting where you can configure GMail's third-party SMTP access :-(

**Comment by dscho** [comment]
*sigh* https://support.google.com/accounts/answer/6010255

**Comment by dscho** [comment]
I've added an App Password, hopefully that works.

**Comment by dscho** [comment]
😓 Phew. That worked: https://public-inbox.org/git/pull.1246.git.1654177966.gitgitgadget@gmail.com/

**Comment by Abhra303** [comment]
Thanks @dscho!!

**Comment by dscho** [comment]
> Is this related to my google account settings?

@Abhra303 no, it was related to GitGitGadget trying to send mails via SMTP and the regular username/password method now being blocked by Google as "too unsafe to allow".

**Comment by sivaraam** [comment]
@Abhra303 I took a quick look at your changes. I can't comment on the formatting changes since I'm new to AsciiDoc, myself. Could you let me know if you've tried to run `make doc` and checked whether the formatting changes improve the output?

On the info you included about the checksum, I suppose it could be elaborated a bit. Like including the information on the algorithm that's used to obtain the checksum.

**Comment by Abhra303** [comment]
> @Abhra303 I took a quick look at your changes. I can't comment on the formatting changes since I'm new to AsciiDoc, myself. Could you let me know if you've tried to run `make doc` and checked whether the formatting changes improve the output?

I used `make doc` but sadly it didn't generate the corresponding html file so that I could check that. But thankfully there is a online asciidoc editor named [asciidoclive](https://asciidoclive.com/edit/scratch/1) which helped the see the resulting output. Sadly I didn't found a way to share it. If you want to look the html page you have to copy-paste the content of `bitmap-format.txt` with the proposed changes there.

> 
> On the info you included about the checksum, I suppose it could be elaborated a bit. Like including the information on the algorithm that's used to obtain the checksum.

Thanks for the suggestion. Will surely include some more details :)

**Pull request closed without merging**
