### PR TITLE
blame: enable funcname blaming with userdiff driver

### PR DESCRIPTION
**Pull request by phil-blain**
Changes since v1:
- patch 1: tweaked the message and took Junio's suggestion to only list the stuck form if the option in 'git-log' and 'gitk'.
- patch 2: very minor formatting changes (removed double quotes)
- patch 3: removed the parentheses as suggested by Junio, and did the same for git-log/gitk.
- patch 4: grammar fix pointed out by Eric
- patch 5: shortened the help text as suggested by Eric
- patch 6: changed the approach by initializing 'sb.path' earlier in 'cmd_blame', along with some of sb's other fields.
- patches 7-8: new cleanup patches following the new patch 6 to simplify the interface of two functions in 'blame.c'

---

This series fixes a bug in `git blame` where any userdiff driver configured
via the attributes mechanism is ignored, which more often than not means that
`git blame -L :<funcname>` dies for paths that have a configured userdiff driver.
That's patch 6/6. 

Patches 1-5 are documentation improvements around the line-log functionality.

Patches 7-8 are code clean-up patches following the changes in patch 6.

The fact that this bug has been present ever since `git blame` learned `-L :<funcname>`  makes me a little sad. I think that the fact that the `diff` attribute (either with a builtin userdiff pattern or with `diff.*.xfuncname` ) influences way more than just the hunk header, but also features like `git log -L`, `git blame -L`, and the different options that I mention in patch 4/6, is not well-known enough. I'm not saying the code or the doc is wrong, but I think it's a visibility issue. Maybe more blog posts about that would help.... I noticed that the "Git Attributes" chapter in the ProGit book [1] does not even mention the builtin userdiff patterns, so I'll probably do a PR there to mention it. Any other ideas for improving discoverability of this very cool feature ?

[1] https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

CC: Thomas Rast <tr@thomasrast.ch>, Eric Sunshine <sunshine@sunshineco.com>, René Scharfe <l.s.r@web.de>

cc: Philippe Blain <levraiphilippeblain@gmail.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
@dscho it seems the Windows Azure build failed in a weird way here:
https://dev.azure.com/gitgitgadget/git/_build/results?buildId=62370&view=logs&jobId=fd490c07-0b22-5182-fac9-6d67fe1e939b&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=70b92200-87db-50c8-35f9-975ba5f9e5b7

The "Skip build if GitHub workflow was configured" task seems to have succeeded (I guess it should then have skipped the rest of the pipeline), but  the "Download git-sdk-64-minimal" task failed (because of availability issue from what I understand)... Do these tasks run concurrently and that's why the whole pipeline is not marked as Passing, like the other Azure pipelines ?


It's no big deal I guess but can be confusing for newcomers ("What is this failing check?!")

**Comment by dscho** [comment]
> 
> 
> @dscho it seems the Windows Azure build failed in a weird way here:
> https://dev.azure.com/gitgitgadget/git/_build/results?buildId=62370&view=logs&jobId=fd490c07-0b22-5182-fac9-6d67fe1e939b&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=70b92200-87db-50c8-35f9-975ba5f9e5b7
> 
> The "Skip build if GitHub workflow was configured" task seems to have succeeded (I guess it should then have skipped the rest of the pipeline), but the "Download git-sdk-64-minimal" task failed (because of availability issue from what I understand)... Do these tasks run concurrently and that's why the whole pipeline is not marked as Passing, like the other Azure pipelines ?
> 
> It's no big deal I guess but can be confusing for newcomers ("What is this failing check?!")

I just restarted that job. It should succeed this time.

**Comment by phil-blain** [comment]
And just now it has restarted itself, despite me not pushing anything new... that's weird.

**Comment by phil-blain** [comment]
Haha ok lol that explains the restart :P

**Comment by dscho** [comment]
> The "Skip build if GitHub workflow was configured" task seems to have succeeded (I guess it should then have skipped the rest of the pipeline), but the "Download git-sdk-64-minimal" task failed (because of availability issue from what I understand)...

I fixed the Pipeline so that the Download step is also skipped (it does not make sense to download the minimal subset of the SDK, only to not do anything with it). And while at it, also the "Publish Test results" steps will be skipped from now on.

**Comment by phil-blain** [comment]
Great, thanks. Far more agile then going through the list :P By the way (just curious), when do you plan to deprecate the GGG Azure pipelines ? it's been quite a while since the GitHub Actions were merged upstream, no ?

**Comment by dscho** [comment]
> when do you plan to deprecate the GGG Azure pipelines ?

There are still a couple of valid PR target branches that do not have GitHub workflow definitions:

```
$ git ls-remote https://github.com/gitster/git | grep refs/heads/ | while read hash name; do git rev-parse -q --verify $hash:.github/workflows/main.yml >/dev/null || echo $name; done
refs/heads/an/merge-single-strategy-optim
refs/heads/bc/filter-process
refs/heads/bc/http-push-flagsfix
refs/heads/bc/push-cas-cquoted-refname
refs/heads/cb/bisect-helper-parser-fix
refs/heads/cb/t4210-illseq-auto-detect
refs/heads/cb/t5608-cleanup
refs/heads/cc/bisect-start-fix
refs/heads/cc/cat-file-usage-update
refs/heads/ct/diff-with-merge-base-clarification
refs/heads/ct/mv-unmerged-path-error
refs/heads/dl/branch-cleanup
refs/heads/dl/diff-usage-comment-update
refs/heads/dl/python-2.7-is-the-floor-version
refs/heads/dl/t-readme-spell-git-correctly
refs/heads/dl/test-must-fail-fixes-5
refs/heads/dr/push-remoteref-fix
refs/heads/ds/commit-graph-bloom-updates
refs/heads/ds/line-log-on-bloom
refs/heads/en/do-match-pathspec-fix
refs/heads/en/fast-import-looser-date
refs/heads/en/fill-directory-exponential
refs/heads/en/sparse-checkout
refs/heads/en/sparse-with-submodule-doc
refs/heads/es/advertise-contribution-doc
refs/heads/es/bugreport-shell
refs/heads/es/get-worktrees-unsort
refs/heads/es/worktree-code-cleanup
refs/heads/es/worktree-duplicate-paths
refs/heads/jb/doc-packfile-name
refs/heads/jk/committer-date-is-author-date-fix
refs/heads/jk/committer-date-is-author-date-fix-simplify
refs/heads/jk/complete-git-switch
refs/heads/jk/diff-memuse-optim-with-stat-unmatch
refs/heads/jk/tests-timestamp-fix
refs/heads/js/checkout-p-new-file
refs/heads/js/fuzz-commit-graph-leakfix
refs/heads/js/msvc-build-fix
refs/heads/js/pu-to-seen
refs/heads/js/reflog-anonymize-for-clone-and-fetch
refs/heads/jt/pretend-object-never-come-from-elsewhere
refs/heads/jx/pkt-line-doc-count-fix
refs/heads/lo/sparse-universal-zero-init
refs/heads/ma/rebase-doc-typofix
refs/heads/maint-2.10
refs/heads/maint-2.11
refs/heads/maint-2.12
refs/heads/maint-2.13
refs/heads/maint-2.14
refs/heads/maint-2.15
refs/heads/maint-2.16
refs/heads/maint-2.17
refs/heads/maint-2.18
refs/heads/maint-2.19
refs/heads/maint-2.20
refs/heads/maint-2.21
refs/heads/maint-2.22
refs/heads/maint-2.23
refs/heads/maint-2.24
refs/heads/maint-2.25
refs/heads/maint-2.26
refs/heads/mf/submodule-summary-with-correct-repository
refs/heads/mk/pb-pretty-email-without-domain-part-fix
refs/heads/mk/use-size-t-in-zlib
refs/heads/mt/entry-fstat-fallback-fix
refs/heads/pb/t4014-unslave
refs/heads/pw/rebase-i-more-options
refs/heads/ra/send-email-in-reply-to-from-command-line-wins
refs/heads/rs/add-index-entry-optim-fix
refs/heads/rs/checkout-no-overlay-pathspec-fix
refs/heads/rs/commit-reach-leakfix
refs/heads/rs/fsck-duplicate-names-in-trees
refs/heads/rs/pull-leakfix
refs/heads/rs/retire-strbuf-write-fd
refs/heads/sg/commit-graph-cleanups
refs/heads/snap
refs/heads/so/rev-parser-errormessage-fix
refs/heads/ta/wait-on-aliased-commands-upon-signal
refs/heads/tb/fix-persistent-shallow
refs/heads/vs/complete-stash-show-p-fix
```

My original idea was to wait until that number was a bit smaller. But maybe that is the wrong measure? Maybe recency should be more relevant? To investigate that, I added the `gitster` remote and did this:

```
$ git for-each-ref --sort=-committerdate refs/remotes/gitster/ | sed -n 's|commit.refs/remotes/gitster|refs/heads|p' | grep refs/heads/ | while read hash name; do git rev-parse -q --verify $hash:.github/workflows/main.yml >/dev/null || echo "$name $(git whatis $hash)"; done
refs/heads/jk/committer-date-is-author-date-fix-simplify 2020451c5bcc (am, sequencer: stop parsing our own committer ident, 2020-10-23)
refs/heads/jk/committer-date-is-author-date-fix 5f35edd9d7eb (rebase: fix broken email with --committer-date-is-author-date, 2020-10-23)
refs/heads/cc/bisect-start-fix 73c6de06aff8 (bisect: don't use invalid oid as rev when starting, 2020-09-25)
refs/heads/pw/rebase-i-more-options 6160b2e9a486 (t3436: do not run git-merge-recursive in dashed form, 2020-08-26)
refs/heads/rs/checkout-no-overlay-pathspec-fix bfda204ade8a (checkout, restore: make pathspec recursive, 2020-08-22)
refs/heads/so/rev-parser-errormessage-fix f649aaaf8227 (revision: fix die() message for "--unpacked=", 2020-08-05)
refs/heads/jb/doc-packfile-name e2bfa50ac3bf (pack-write/docs: update regarding pack naming, 2020-07-22)
refs/heads/jt/pretend-object-never-come-from-elsewhere a64d2aae5a59 (sha1-file: make pretend_object_file() not prefetch, 2020-07-21)
refs/heads/bc/push-cas-cquoted-refname cd85b447bfc0 (remote-curl: make --force-with-lease work with non-ASCII ref names, 2020-07-21)
refs/heads/ct/mv-unmerged-path-error 9b906af657d4 (git-mv: improve error message for conflicted file, 2020-07-20)
refs/heads/en/fill-directory-exponential cada7308ade0 (dir: check pathspecs before returning `path_excluded`, 2020-07-20)
refs/heads/dl/branch-cleanup d223e85407f7 (t3200: don't grep for `strerror()` string, 2020-07-18)
refs/heads/js/pu-to-seen ca8bb509d23e (gitworkflows.txt: fix broken subsection underline, 2020-07-18)
refs/heads/rs/add-index-entry-optim-fix a98f7fb36679 (read-cache: remove bogus shortcut, 2020-07-16)
refs/heads/jk/tests-timestamp-fix 180a4d76ac8f (t9100: stop depending on commit timestamps, 2020-07-15)
refs/heads/ct/diff-with-merge-base-clarification 78b76d310f3e (git-diff.txt: reorder possible usages, 2020-07-13)
refs/heads/ma/rebase-doc-typofix 81de0c01cf72 (git-rebase.txt: fix description list separator, 2020-07-09)
refs/heads/mt/entry-fstat-fallback-fix 35e6e212fdea (entry: check for fstat() errors after checkout, 2020-07-08)
refs/heads/tb/fix-persistent-shallow ce16364e897e (commit.c: don't persist substituted parents when unshallowing, 2020-07-08)
refs/heads/ta/wait-on-aliased-commands-upon-signal c0d73a59c956 (Wait for child on signal death for aliases to externals, 2020-07-07)
[...]
```

As you can see, there are two branches that are not even a week old that miss a definition for a GitHub workflow. The next branch without such a definition is barely older than a month, and the next two after that barely older than two months.

I'd like to wait a little bit longer.

**Comment by phil-blain** [comment]
Ah ok, I understand. I did not have that fact in mind (that you can target topic branches and that the pipelines run against the merge commit between the tips of the target branch and base branche (right?))

That and the fact that Junio bases topic branches on old commits.

**Comment by phil-blain** [comment]
@dscho it appears this PR was not submitted to the list ! Would you be so kind to look into that ? (No rush though)

**Comment by phil-blain** [comment]
I mean, I did receive the emails myself, but the thread is not found on lore...

**Comment by dscho** [comment]
> it appears this PR was not submitted to the list ! Would you be so kind to look into that ? (No rush though)

I guess this problem resolved itself, as I can see https://lore.kernel.org/git/pull.774.git.1603889270.gitgitgadget@gmail.com/ including replies.

**Pull request closed without merging**
