### PR TITLE
doc: clarify description of 'submodule.recurse'

### PR DESCRIPTION
**Pull request by phil-blain**
The current wording confused at least one user [1], so let's clarify that.

[1] https://stackoverflow.com/questions/4611512/is-there-a-way-to-make-git-pull-automatically-update-submodules/49427199?noredirect=1#comment119208094_49427199

CC: Damien Robert <damien.olivier.robert@gmail.com>
CC: Stefan Beller <stefanbeller@gmail.com>
CC: Brandon Williams <bwilliams.eng@gmail.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
@dscho I think something changed with the permissions on the GitHub side, the GitHub Actions workflow are not running and I see
> 2 workflows awaiting approval
> First-time contributors need a maintainer to approve running workflows. Learn more.

Is it a change you made ? Also something is weird because I'm not a first-time contributor...

**Comment by dscho** [comment]
>  I'm not a first-time contributor...

I know, and I wonder myself what constitutes a "first-time contributor". Someone without any merged PR? Someone without any commits? Dunno. But yes, I have to approve your runs all the time, and it is a bit annoying.

On a bright note, you probably noticed that [the workflow ran in your fork](https://github.com/phil-blain/git/actions/runs/1036124157) and passed. So I would think that it is not _all_ that crucial that the _PR_ build passes too.

**Comment by phil-blain** [comment]
yes, I noticed that it ran in my fork, thanks. I just wanted to let you know (and see if a fix was in the making fr this hurdle).. The doc for this new limitation (https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) does not mention how a contributor is "allow-listed", but I'm guessing it is when the "merge" button is pushed, which never happens here...

**Pull request closed without merging**
