### PR TITLE
Dir rename fixes

### PR DESCRIPTION
**Pull request by newren**
This series improves a couple things found after looking into things Dscho flagged:
  * clarify and slightly restructure code in the get_renamed_dir_portion() function
  * extend support of detecting renaming/merging of one directory into another to support the root directory as a target directory

First patch best viewed with a --histogram diff (sorry, gitgitgadget does not yet know how to generate those).

Changes since v1:
  * Incorporated code cleanups suggested by Dscho
  * Fixed to work with an alternate rename-to-root-directory case (end_of_new == NULL), with new testcase
  * Added a new patch to the end of the series to stop making setup tests be part of a separate test_expect_success block.

Cc: Johannes Schindelin Johannes.Schindelin@gmx.de

### CODE REVIEW

**Comment by dscho** [comment]
Are you planning on re-doing the entire series? It already made it to `next`...

**Comment by newren** [comment]
Yes, it made it to next...but then was reverted out of next specifically to allow resending with fixes.  Sorry for the delay, I'll get it out later today.

**Comment by newren** [comment]
Looks like those CI failures were for installing git-lfs, infrastructure not under my control and not used by my tests.  Since I can't retrigger, I guess I just ignore those?

**Pull request closed without merging**
