### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by algonell**
Fix typos in documentation, comments, etc.

cc: Eric Sunshine <sunshine@sunshineco.com>
cc: "Kristoffer Haugsbakk" <kristofferhaugsbakk@fastmail.com>

### CODE REVIEW

**Comment by algonell** [comment]
@dscho absolutely, I'm a bit worried about the OS X failing / stuck jobs...

**Comment by dscho** [comment]
> I'm a bit worried about the OS X failing / stuck jobs...

Right, that's something nobody seems to take care of.

On the other hand, since your typo fixes do not touch code, you can ignore failing CI builds, right?

**Comment by algonell** [comment]
Well yes, but one of my `uptodate -> up to date` changed in `unpack-trees.c` requires the according `t7110-reset-merge.sh` test to be updated as well (did not commit this one yet).

That's why I'm extra cautious about it.

So should I submit?

**Comment by dscho** [comment]
> one of my `uptodate -> up to date` changes in `unpack-trees.c` requires the according `t7110-reset-merge.sh` test to be updated as well (did not commit this one yet).
> 
> That's why I'm extra cautious about it.
> 
> So should I submit?

Does this change a user-visible message? If so, it might be fraught with peril to change it: Third-party applications do not enjoy any consistent error types being reported by Git, so they have to parse the error messages. And if those error messages change, those applications break.

**Comment by algonell** [comment]
Agreed, a potential breaking change, that's why I skipped it.

**Comment by algonell** [comment]
Thank you Eric!

Sure, my secret sauce is [codespell](https://github.com/codespell-project/codespell).

**Comment by dscho** [comment]
> Thank you Eric!
> 
> Sure, my secret sauce is [codespell](https://github.com/codespell-project/codespell).

@algonell please reply on-list.

**Comment by dscho** [comment]
@algonell did you really mean to close this PR? If you plan on submitting a v2, GitGitGadget is set up to do that only when `/submit`ing from the _same_ PR, not from a new one.

**Comment by algonell** [comment]
@dscho apologies for the extra noise...

Actually I wanted to sync and rebase some new things (from my next branch)

I think I better to send patches via `git send-email` from now on (already started).

Thinking out loud: the bot should not close an 'empty' PR...?!

**Comment by dscho** [comment]
> Thinking out loud: the bot should not close an 'empty' PR...?!

That's not the bot, that's GitHub doing that.

**Pull request closed without merging**
