### PR TITLE
strlcpy(): safer and faster version

### PR DESCRIPTION
**Pull request by amakukha**
cc: Jeff King <peff@peff.net>
cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>

### CODE REVIEW

**Comment by dscho** [comment]
@amakukha since the cover letter (i.e. the PR description) repeated the commit message, I allowed myself to remove it.

**Comment by amakukha** [comment]
@dscho , thanks. 

I'll add to the commit message, however, that I checked the usage of this function in this repository, and the return value of strlcpy() is only checked in one place in file daemon.c. And my change does not change the behaviour of that line. So, in essence, it's just refactoring.

**Comment by amakukha** [comment]
Yes, I agree that changing the semantics was not a good idea. So we can
just close this MR.

Personally, I've never seen code that relies on the the fact that strlcpy
returns strlen(src) even if src is much larger than dst buffer. The comment
to the OpenBSD's strlcpy says that if return value is ">= dsize" then it
means that truncation occured. My version complies with that notion.

However, I do admit that there _could_ be someone somewhere who relies on
this strange behaviour.

So, I think a better way is just not to use strlcpy at all.

Thanks for your comments!

**Comment by dscho** [comment]
> we can just close this MR.

Please do so.

**Pull request closed without merging**
