### PR TITLE
Refactor list_cmds function

### PR DESCRIPTION
**Pull request by thiago16fca**
This PR just improves list_cmds function code reading.

### CODE REVIEW

**Comment by dscho** [comment]
@thiago16fca what is the goal of this PR?

**Comment by dscho** [comment]
> @thiago16fca what is the goal of this PR?

Or put another way: if the primary aim is indeed, as the PR description says, to improve the readability of the code in question, I have to admit that I do not find the result any more readable than the original...

Nevertheless, if you want to present this to the Git mailing list, please do fix the indentation (Git uses tabs, not spaces), and the commit message (it needs to be much more verbose).

**Comment by thiago16fca** [comment]
> @thiago16fca what is the goal of this PR?

To improve readability in if and else if statements, because it's easier to read a sentence that describes what a function does rather than a function call.

**Comment by webstech** [comment]
> To improve readability

At what cost?  Sure this is not a highly used function but it is not a good pattern to do six function calls when only one may be needed.  Would this be easier to read (untested)?

```
static int match_token(const char *spec, int len, const char *token, size_t token_len)
{
	return len == token_len && !strncmp(spec, token, token_len);
}
...
#define is_token(x) match_token(spec, len, x, sizeof(x) - 1)

	while (*spec) {
		const char *sep = strchrnul(spec, ',');
		int len = sep - spec;

		if (is_token("builtins"))
			list_builtins(&list, 0);
		else if (is_token("main"))
...
#undef is_token
```
I have no idea if using macros like this is accepted in git.

**Comment by dscho** [comment]
> Git uses tabs with 8 spaces ?

Yes. (Just look at the existing code :grin:)

**Comment by thiago16fca** [comment]
> > Git uses tabs with 8 spaces ?
> 
> Yes. (Just look at the existing code 😁)

I looked, but didn't see that. I guess is because my github tab size is setted to 2.

**Pull request closed without merging**
