### PR TITLE
fetch-pack: redact packfile urls in traces

### PR DESCRIPTION
**Pull request by ifradeo**
Changes since v6:
  - Use specific hash sizes instead of hexsz
  - Remove unnecessary env vars in tests
  - Added comment on bit toggle

Changes since v5:
  - Use hexsz instead of hardcoded hash sizes
 
Changes since v4:
  - Use "uri" instead of "url"
  - Look specifically for a line with packfile-uri format (instead of for a URL in general)
  - Limit the redacting to the packfile-uri section in do_fetch_pack_v2
  - Use "%.*s" instead of duplicating parts of the string to print
 
Changes since v3:
  - Enable redacting URLs for all sections
  - Redact only URL path (it was until the end of line)
  - Redact URL in die() with more friendly message
  - Update doc to mention that packfile URIs are also redacted.
 
Changes since v2:
  - Redact only the path of the URL
  - Test are now strict, validating the exact line expected in the log

Changes since v1:
  - Removed non-POSIX flags in tests
  - More accurate regex for the non-encrypted packfile line
  - Dropped documentation change
   - Dropped redacting the die message in http-fetch

cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Eric Sunshine <sunshine@sunshineco.com>
cc: Jonathan Tan <jonathantanmy@google.com>

### CODE REVIEW

**Comment by ifradeo** [comment]
On Mon, Oct 11, 2021 at 1:44 PM gitgitgadget[bot]
***@***.***> wrote:
>
> On the Git mailing list, Junio C Hamano wrote (reply to this):
>
> It of course is a different matter if the explained idea is
> agreeable, though ;-).  Hiding the entire packet, based on the "it
> might be in some setups" seems a bit too much.
>
> Is it often the case that the whole URI is sensitive, or perhaps
> leading "<scheme>://<host>/pack-<abc>.pack" part is not sensitive at
> all, and what follows after that "public" part has some "nonce"
> material that makes it sensitive?

In the specific case I am working on, the path of the URL is an
encrypted string that shouldn't be completely exposed (exposing part
of it would be fine). In general, I think we can assume that
<scheme>://<host>/ are always "public" but the path could be
sensitive.

We could redact only the path (<scheme>://<host>/REDACTED), or even a
fixed length of the URL? (<scheme>://<host>/pack-<xxREDACTED).

In the next patch version I go with redacting the path.

>
> > Changes since v1:
...
> [...]  Please write such
> material below the three-dash line.
...
>
> And there is no need to duplicate the log message here ;-)

Thanks! I hope I got it right this iteration. Maybe the PR template in
github could mention this? It wasn't clear to me the relation between
PR comment and commit message.

> So "original_options" is used to save away the reader->options so
> that it can be restored before returning to our caller?
>
> OK (it may be more common in this codebase to call such a variable
> "saved_X", though).

Done.


> > + grep "clone< <redacted>" log
>
> This checks only that "redacted" string appears, but what the theme
> of the change really cares about is different, no?  You want to
> ensure that no sensitive substring of the URI appears in the log.

Now the tests check strictly the expected line.

Thanks,

Ivan

**Comment by dscho** [comment]
> 
> On Mon, Oct 11, 2021 at 1:44 PM gitgitgadget[bot] ***@***.***> wrote: On the Git mailing list, Junio C Hamano wrote (reply to this): It of course is a different matter if the explained idea is agreeable, though ;-). Hiding the entire packet, based on the "it might be in some setups" seems a bit too much. Is it often the case that the whole URI is sensitive, or perhaps leading "<scheme>://<host>/pack-<abc>.pack" part is not sensitive at all, and what follows after that "public" part has some "nonce" material that makes it sensitive?
> In the specific case I am working on, the path of the URL is an encrypted string that shouldn't be completely exposed (exposing part of it would be fine). In general, I think we can assume that <scheme>://<host>/ are always "public" but the path could be sensitive. We could redact only the path (<scheme>://<host>/REDACTED), or even a fixed length of the URL? (<scheme>://<host>/pack-<xxREDACTED). In the next patch version I go with redacting the path.
> > Changes since v1:
> ...
> [...] Please write such material below the three-dash line.
> ...
> And there is no need to duplicate the log message here ;-)
> Thanks! I hope I got it right this iteration. Maybe the PR template in github could mention this? It wasn't clear to me the relation between PR comment and commit message.
> So "original_options" is used to save away the reader->options so that it can be restored before returning to our caller? OK (it may be more common in this codebase to call such a variable "saved_X", though).
> Done.
> > + grep "clone< <redacted>" log This checks only that "redacted" string appears, but what the theme of the change really cares about is different, no? You want to ensure that no sensitive substring of the URI appears in the log.
> Now the tests check strictly the expected line. Thanks, Ivan

@ifradeo please see https://github.com/gitgitgadget/gitgitgadget/wiki/ReplyToThis for guidance how to reply on-list (your reply was as a PR comment, and won't be seen e.g. by Junio).

**Pull request closed without merging**
