### PR TITLE
git-p4: use raw string literals for regular expressions

### PR DESCRIPTION
**Pull request by Bekenn**
Changes since v1:

- Updated commit message to include the Python version where the diagnostics were observed.

### CODE REVIEW

**Comment by Bekenn** [comment]
@dscho I've updated my GitHub profile to include my preferred email address; is there anything more I need to do to retrigger the bot?

**Comment by dscho** [comment]
> @dscho I've updated my GitHub profile to include my preferred email address; is there anything more I need to do to retrigger the bot?

Nope, but you can verify that everything works by issuing `/preview`.

**Comment by Bekenn** [comment]
@dscho It looks like this still hasn't gone out to the mailing list; is that because of the failing CI job?  Is there a way for me to kick it?

**Comment by dscho** [comment]
> It looks like this still hasn't gone out to the mailing list; is that because of the failing CI job?

No, it's because a `/preview` only goes out to your own email address, to test, like. You need to `/submit` if everything worked all right with the `/preview`.

**Comment by Bekenn** [comment]
Ah, I missed that there was a submit step.  Thanks!

**Pull request closed without merging**
