### PR TITLE
2.35.1.txt: clarify the rebase/stash regression

### PR DESCRIPTION
**Pull request by newren**
I haven't seen the release notes go out; I'm hoping this patch is seen in time...

### CODE REVIEW

**Comment by dscho** [comment]
I guess somebody finished a release quickly, in order to enjoy a weekend... :grin:

**Comment by newren** [comment]
> I guess somebody finished a release quickly, in order to enjoy a weekend... grin

Yeah, I can't fault him for that.  Just wish I would have been able to notice and respond sooner.  Oh, well.

**Comment by newren** [comment]
I suspect this one isn't being picked up; probably too late to help much anyway...

**Pull request closed without merging**
