### PR TITLE
Fix: wrongly put comment for __git_complete_worktree_paths completion helper function

### PR DESCRIPTION
**Pull request by imomaliev**
git completion script fails for zsh

```console
$ git worktree remove [TAB]
$ git worktree remove __git_complete_worktree_paths:7: command not found: #
```

### CODE REVIEW

**Comment by imomaliev** [comment]
@dscho thanks. Is there a way to provide email with setting it public in github?

**Comment by dscho** [comment]
Unfortunately, not at the moment.

**Comment by imomaliev** [comment]
Looks like either way patch was sent. So maybe there is no need to provide public email. But if it still required, I will update my settings

**Pull request closed without merging**
