### PR TITLE
builtin/remote.c: teach `-v` to list filters for promisor remotes

### LINKED ISSUE #1211: Filters from promisor remotes (partial clone) should be listed by `git remote -v`
It would be nice for promisor remotes to be identified as such in the output of `git remove -v`, something like this maybe:
~~~bash
$ git config --get remote.origin.partialCloneFilter
blob:none
$ git remote -v
origin	git@github.com:phil-blain/github-docs (fetch) [blob:none]
origin	git@github.com:phil-blain/github-docs (push)
~~~

### PR DESCRIPTION
**Pull request by Abhra303**
Fixes #1211 [1]

Changes since v3:
- tests are moved to `t5505-remote.sh`
- Documentation improved
- Added `Closes` trailer in the commit message

Changes since v2:
- added more test cases
- fixed broken indentations

Changes since v1:
- updated documentation
- renamed url_buf into remote_info_buf

[1] https://github.com/gitgitgadget/git/issues/1211

cc: Philip Oakley <philipoakley@iee.email>
cc: Junio C Hamano <gitster@pobox.com>
cc: Philippe Blain <levraiphilippeblain@gmail.com>
cc: Taylor Blau <me@ttaylorr.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
Hi @Abhra303, thanks for having a go at that! I encourage you to send it to the list for review :)

**Comment by Abhra303** [comment]
@phil-blain , Yes I will. I was waiting for the tests to complete.

Thanks :)

**Pull request closed without merging**
