### PR TITLE
Remove fast export munging

### PR DESCRIPTION
**Pull request by newren**
Let's see if this update also works on Windows.

### CODE REVIEW

**Comment by dscho** [comment]
FTR you could reopen [the previous PR](https://github.com/gitgitgadget/git/pull/187) and force-push... ;-)

**Comment by newren** [comment]
@dscho: I tried to reopen the previous one, but the "reopen" button was greyed out for me.  So, I created this new one instead.

**Comment by newren** [comment]
...and apparently it was grayed out because I had deleted the related branch; if I had re-created it... oh well, that's what I get for using two similarly named branches.

**Comment by dscho** [comment]
> it was grayed out because I had deleted the related branch; if I had re-created it... oh well, that's what I get for using two similarly named branches.

TBH I do not know whether that works. I did know that PRs are automatically closed when the corresponding branch is deleted, and failed to mention that: sorry!

**Pull request closed without merging**
