### PR TITLE
List all guides in git(1)

### PR DESCRIPTION
**Pull request by phil-blain**
Changes since v2:
- Split the third commit following Junio's suggestion

Question for Junio:
Since the new commit 3/4 comes entirely from your suggestion, 
I've attributed authorship to you, but I've added my own sign-off because
Gitgitgadget requires sign-off on each commit. Please let me know 
if I should have proceeded differently.

v2:
- Incorporated Junio's suggestion to reduce duplication.

v1: 
This series adds a list of the guides to git(1).

The first commit adds the misssing guides 'gitcredentials' and
'gitremote-helpers' to command-list.txt. The only missing guide after this
change is 'gitweb.conf', but I think this one is obscure anough, and already
linked to in 'gitweb.txt', that it does not matter much.

The second commit drops the usage of 'common' and 'useful' for guides. This was
suggested as one of two ways forward by Duy in [1] but was not commented on.
I'm CC'ing the people that were CC'ed on that message.

The third commit tweaks 'Documentation/cmd-list.perl' so that it also generates
a list of the guides, which gets included in 'git.txt'. I chose to put this
list just after the end of the list of commands.

[1] https://lore.kernel.org/git/CACsJy8ADj-bTMYDHxRNLOMppOEdPbVwL49u3XCfNBCmoLLZo+A@mail.gmail.com/

CC: Nguyễn Thái Ngọc Duy <pclouds@gmail.com>, Philip Oakley <philipoakley@iee.email>, "Eric Sunshine" <sunshine@sunshineco.com>, "SZEDER Gábor" <szeder.dev@gmail.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
Hi @dscho, since GitHub actions were introduced in git.git I'm really confused with all the CI jobs (especially all the Windows ones)... is there somewhere where the purpose of the different jobs is documented ? Also I find it weird that most Azure jobs succeed but in under a minute, it seems unlikely the whole test suite runs in such a short time :P 

Also, I'm having failures in the Windows job, related to downloading artifacts it seems, I have the feeling this part of the CI scripts is not very robust.. is there a way that could be improved ?

**Comment by dscho** [comment]
> since GitHub actions were introduced in git.git I'm really confused with all the CI jobs (especially all the Windows ones)... is there somewhere where the purpose of the different jobs is documented ?

Unfortunately not.

> Also I find it weird that most Azure jobs succeed but in under a minute, it seems unlikely the whole test suite runs in such a short time :P

The problem is that I cannot disable the Azure Pipeline _just_ for branches containing `.github/workflows/main.yml`. (Maybe there is a way, if there is, I haven't found it.) So the Azure Pipeline itself looks for the presence of that file, and just skips everything if it is found.

> Also, I'm having failures in the Windows job, related to downloading artifacts it seems, I have the feeling this part of the CI scripts is not very robust.. is there a way that could be improved ?

Yes, I noticed that, too. There is unfortunately nothing on our side that we can do about it, I don't think. I did notice that it has become more robust, though, in the last couple weeks (with occasional hiccups).

**Comment by phil-blain** [comment]
Thanks for getting back to me. So the Azure pipelines are kept for people submitting PRs based on old versions of the repo, before the Github actions were introduced?

**Comment by dscho** [comment]
Yes.

**Pull request closed without merging**
