### PR TITLE
ref-filter: handle CRLF at end-of-line more gracefully

### PR DESCRIPTION
**Pull request by phil-blain**
Changes since v4 :

- tweaked the wording of both commit messages to not call the behaviour a bug
- added `|| return 1` in one test - that had already been squashed in by Junio

---

The ref-filter code does not correctly handle commit or tag messages that
use CRLF as the line terminator. Such messages can be created with the 
`--cleanup=verbatim` option of `git commit` and `git tag`, or by using `git
commit-tree` directly.

The function find_subpos in ref-filter.c looks for two consecutive '\n'
to find the end of the subject line, a sequence which is absent in
messages using CRLF. This results in the whole message being parsed as
the subject line (`%(contents:subject)`), and the body of the message
(`%(contents:body)`) being empty.

Moreover, in copy_subject, '\n' is replaced by space, but '\r' is
untouched.

This behaviour is a regression for `git branch --verbose`, which
bisects down to 949af06 (branch: use ref-filter printing APIs,
2017-01-10).

The first patch hardens the code in ref-filter.c to handle these messages more gracefully and adds a test script to check 
that the ref-filter and pretty APIs deal correctly with CRLF messages.

The second patch adds tests that check the behaviour of `git log` and 
`git show` in the presence of CRLF in messages, to prevent futur regressions.

Cc: Michael J Gruber <git@grubix.eu>, Matthieu Moy <git@matthieu-moy.fr>, John Keeping <john@keeping.me.uk>, Karthik Nayak <karthik.188@gmail.com>, Jeff King <peff@peff.net>, Alex Henrie <alexhenrie24@gmail.com>
cc: Eric Sunshine <sunshine@sunshineco.com>
cc: Junio C Hamano <gitster@pobox.com>

cc: Philippe Blain <levraiphilippeblain@gmail.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
Hi @dscho, the "vs-build" task seems to be failing because of an unrelated (to my changes) error from Cmake:
```
-- Detecting C compile features - done
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
Call Stack (most recent call first):
-- Configuring incomplete, errors occurred!
See also "D:/a/git/git/CMakeFiles/CMakeOutput.log".
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:126 (find_package)
```

Just thought I'd let you know.

**Comment by dscho** [comment]
> the "vs-build" task seems to be failing because of an unrelated (to my changes) error from Cmake:
> 
> ```
> -- Detecting C compile features - done
> CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
>   Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
> Call Stack (most recent call first):
> -- Configuring incomplete, errors occurred!
> See also "D:/a/git/git/CMakeFiles/CMakeOutput.log".
>   C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
>   C:/Program Files/CMake/share/cmake-3.18/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>   CMakeLists.txt:126 (find_package)
> ```

That's strange, I did not see any other run failing in a similar way, it might be a new bug.

**Comment by phil-blain** [comment]
(note to self)

The failures in the "linux-clang" are super weird, the commit hashes are not the same as in the other jobs (!!):
```diff
expecting success of 3203.13 'git branch -v works with CRLF input': 
	cat >expect <<-EOF &&
  branch-one                                      139b20d two
  branch-two                                      d79ce16 one
  crlf                                            2113b0e Subject first line
  crlf-empty-lines-after-subject                  0a9530d Subject first line
  crlf-two-line-subject                           f9ded1f Subject first line Subject second line
  crlf-two-line-subject-no-body                   8ca104a Subject first line Subject second line
  crlf-two-line-subject-no-body-trailing-newline  52360ed Subject first line Subject second line
  crlf-two-line-subject-no-body-trailing-newline2 9ff60d6 Subject first line Subject second line
* master                                          139b20d two
	EOF
	git branch -v >actual &&
	test_cmp expect actual

+ cat
+ git branch -v
+ test_cmp expect actual
+ test 2 -eq 2
+ eval diff -u "$@"
+ diff -u expect actual
--- expect	2020-10-10 19:58:04.481749992 +0000
+++ actual	2020-10-10 19:58:04.485750391 +0000
@@ -1,9 +1,9 @@
-  branch-one                                      139b20d two
-  branch-two                                      d79ce16 one
-  crlf                                            2113b0e Subject first line
-  crlf-empty-lines-after-subject                  0a9530d Subject first line
-  crlf-two-line-subject                           f9ded1f Subject first line Subject second line
-  crlf-two-line-subject-no-body                   8ca104a Subject first line Subject second line
-  crlf-two-line-subject-no-body-trailing-newline  52360ed Subject first line Subject second line
-  crlf-two-line-subject-no-body-trailing-newline2 9ff60d6 Subject first line Subject second line
-* master                                          139b20d two
+  branch-one                                      06ccb23 two
+  branch-two                                      d8f7d82 one
+  crlf                                            a930c45 Subject first line
+  crlf-empty-lines-after-subject                  f6af2f6 Subject first line
+  crlf-two-line-subject                           d1d64e4 Subject first line Subject second line
+  crlf-two-line-subject-no-body                   0456b69 Subject first line Subject second line
+  crlf-two-line-subject-no-body-trailing-newline  81f22e7 Subject first line Subject second line
+  crlf-two-line-subject-no-body-trailing-newline2 9264d38 Subject first line Subject second line
+* master                                          06ccb23 two
+ test xexpect = x-
+ test -e expect
+ test xactual = x-
+ test -e actual
+ return 1
error: last command exited with $?=1
not ok 13 - git branch -v works with CRLF input
```

and

```diff
expecting success of 4202.10 'oneline with CRLF messages': 
	echo "002093e Subject first line" >expect &&
	git log --oneline -1 crlf >actual-branch &&
	git log --oneline -1 tag-crlf >actual-tag &&
	test_cmp expect actual-branch &&
	test_cmp expect actual-tag &&
	echo "6f814b0 Subject first line" >expect &&
	git log --oneline -1 crlf-empty-lines-after-subject >actual-branch &&
	git log --oneline -1 tag-crlf-empty-lines-after-subject >actual-tag &&
	test_cmp expect actual-branch &&
	test_cmp expect actual-tag &&
	echo "8c58a85 Subject first line Subject second line" >expect &&
	git log --oneline -1 crlf-two-line-subject >actual-branch &&
	git log --oneline -1 tag-crlf-two-line-subject >actual-tag &&
	test_cmp expect actual-branch &&
	test_cmp expect actual-tag

+ echo 002093e Subject first line
+ git log --oneline -1 crlf
+ git log --oneline -1 tag-crlf
+ test_cmp expect actual-branch
+ test 2 -eq 2
+ eval diff -u "$@"
+ diff -u expect actual-branch
--- expect	2020-10-10 20:00:07.328957655 +0000
+++ actual-branch	2020-10-10 20:00:07.344958997 +0000
@@ -1 +1 @@
-002093e Subject first line
+5a8a48f Subject first line
+ test xexpect = x-
+ test -e expect
+ test xactual-branch = x-
+ test -e actual-branch
+ return 1
error: last command exited with $?=1
not ok 10 - oneline with CRLF messages
```

So I guess that would mean there is something different in the commit themselves...

**Comment by dscho** [comment]
On my phone, so I cannot check: does this have anything to do with SHA-256? (`linux-clang` runs the tes suite twice, once with SHA-1 and the with -256).

**Comment by phil-blain** [comment]
yes that was indeed the cause (thanks a lot for answering! I started with "note-to-self" so I was mainly talking to myself).

**Comment by phil-blain** [comment]
Although I do have a question for you: when I push this branch, the GitHub Actions workflow **in my fork** fails in the "ci-config" job: 
https://github.com/phil-blain/git/runs/1238660958
It's the new check to see if the tree was already build that fails:
```
Run actions/github-script@v3
TypeError: Cannot read property 'tree_id' of null
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:5277:56), <anonymous>:27:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:5303:20)
Error: Unhandled error: TypeError: Cannot read property 'tree_id' of null
```

**Comment by dscho** [comment]
> Run actions/github-script@v3
> TypeError: Cannot read property 'tree_id' of null
>     at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:5277:56), <anonymous>:27:35)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async main (/home/runner/work/_actions/actions/github-script/v3/dist/index.js:5303:20)
> Error: Unhandled error: TypeError: Cannot read property 'tree_id' of null

See https://github.com/dscho/git/runs/1239247226?check_suite_focus=true for my debug run. There is apparently still a record of a certain run (https://github.com/phil-blain/git/actions/runs/161326755) from beginning of July, where the record does not have a `head_commit` attribute.

Will fix.

**Comment by dscho** [comment]
> Will fix.

See https://github.com/gitgitgadget/git/pull/748.

**Comment by phil-blain** [comment]
> > Will fix.
> 
> See #748.

Great! Thanks for figuring that out.

**Pull request closed without merging**
