### PR TITLE
sparse-checkout: fix segfault on malformed patterns

### PR DESCRIPTION
**Pull request by derrickstolee**
This series fixes some issues with parsing sparse-checkout patterns when core.sparseCheckoutCone is enabled but the sparse-checkout file itself contains patterns that don't match the cone mode format.

The first patch fixes a segfault first reported in [1]. The other two patches are from an earlier submission [2] that never got picked up and I lost track of. There was another patch involving 'git sparse-checkout init --cone' that isn't necessary, especially with Elijah doing some work in that space right now.

[1] https://github.com/git-for-windows/git/issues/3498
[2] https://lore.kernel.org/git/pull.1043.git.1632160658.gitgitgadget@gmail.com

Thanks,
-Stolee

Update in v4
------------

* For added precaution, this kind of unexpected duplicate pattern will disable cone mode matching.
* Tests are updated to verify this new behavior.

Updates in v2 and v3
--------------------

* I intended to fix a typo in a patch, but accidentally sent the `amend!` commit in v2
* v3 has the typo fix properly squashed in.
* Added Elijah's review.

cc: me@ttaylorr.com
cc: newren@gmail.com
cc: vdye@github.com
cc: Derrick Stolee <stolee@gmail.com>

### CODE REVIEW

**Review by webstech — COMMENTED** [review]
Commit 7bacb3760f3d8d55b9a8d370642b093e9c60e9a6 has no content.  Is that intentional?

@dscho GitGitGadget may need to handle this.

**Comment by dscho** [comment]
> Commit 7bacb3760f3d8d55b9a8d370642b093e9c60e9a6 has no content.  Is that intentional?

Oh darn it, I did not even notice!

Yes, it is intentional, it's an `amend!` commit. This (relatively new) feature allows to reword a commit message, with the same ease as a `fixup!` allows amending the patch.

> @dscho GitGitGadget may need to handle this.

That's a really good point.

**Comment by derrickstolee** [comment]
> > Commit [7bacb37](https://github.com/gitgitgadget/git/commit/7bacb3760f3d8d55b9a8d370642b093e9c60e9a6) has no content.  Is that intentional?
> 
> Oh darn it, I did not even notice!
> 
> Yes, it is intentional, it's an `amend!` commit. This (relatively new) feature allows to reword a commit message, with the same ease as a `fixup!` allows amending the patch.
> 
> > @dscho GitGitGadget may need to handle this.
> 
> That's a really good point.

Whoops! I definitely should have squashed that in....

**Comment by webstech** [comment]
> > @dscho GitGitGadget may need to handle this.
> 
> That's a really good point.

Two possible changes:
1. Change linting to flag commit messages starting with `squash!`, `fixup!` or `amend!`.  
2. Reject empty patches in the future patch linting code (which I plan to get back to at some point).  It would appear the git project does not want empty patches since git itself does not generate emails for them.

**Pull request closed without merging**
