### PR TITLE
rebase: fix typo in autosquash documentation

### PR DESCRIPTION
**Pull request by rmacklin**

### CODE REVIEW

**Comment by rmacklin** [comment]
Side note re: this:

> WARNING: rmacklin has no public email address set on GitHub;
> GitGitGadget needs an email address to Cc: you on your contribution, so that you receive any feedback on the Git mailing list. Go to https://github.com/settings/profile to make your preferred email public to let GitGitGadget know which email address to use.

It seems inaccurate - I did get CCed - it used the email address that I committed with (which is what I was hoping it would do). Maybe we should remove this warning from the comment..? cc @dscho

**Comment by dscho** [comment]
It was a coincidence that it worked:

- There was only a single commit, i.e. no cover letter
- The commit was authored by you

If either had not been the case, you would not have been Cc:ed, would have missed the reviewers' replies, reviewers would have become frustrated, etc

This warning, therefore, is still relevant.

**Comment by rmacklin** [comment]
Gotcha, thanks for the clarification. Perhaps we could detect when those two conditions are met before posting the warning?

But also, I wouldn't have missed the replies if I was actively monitoring the thread on my own, or even if I was only monitoring this PR given that GitGitGadget forwards the replies as PR comments, right? Anyway, I'm fine with leaving the warning as is, just sharing some thoughts. Again, thank you for making this tool!

**Pull request closed without merging**
