### PR TITLE
typo in glossary content

### PR DESCRIPTION
**Pull request by robi-y**
The text was somewhat confusing between the revision itself and the
author.

Signed-off-by: Reuven Yagel <robi@post.jce.ac.il>

### CODE REVIEW

**Comment by robi-y** [comment]
Changes since v1:
- Fixed the commit message according to the contribution message above

**Comment by robi-y** [comment]
Hello :-)
I agree that your phrasing is less confusing, but I think the original text does not talk about the author but rather on the revision itself (at least in it's current state),  so maybe just correct by:
*t*his *newer* revision
?
Thanks!

**Comment by robi-y** [comment]
Changes since v2:
- Fixed the documentation text according to a conversation with @Junio (sorry, but I'm still not sure how to properly reply through the gitgitgadget mechanism)
- Fixed the commit message according to the contribution above

**Comment by dscho** [comment]
> 
> 
> Changes since v2:
> 
>     * Fixed the documentation text according to a conversation with @junio (sorry, but I'm still not sure how to properly reply through the gitgitgadget mechanism)
> 
>     * Fixed the commit message according to the contribution above

My idea with GitGitGadget was to edit the [first comment](https://github.com/gitgitgadget/git/pull/957#issue-647288678), adding this information (and removing the welcome message that was targeting you, the contributor).

I am sorry that this is all very much complicated, with subtle expectations. Like the thing where Junio does not like to be addressed with a `@` before their name. Sorry!

**Comment by robi-y** [comment]
Hi, I hope next time, will be easier :-)
I edited the first comment according to the latest commit message.
(BAH: I had a typo in `author`, should I correct the commit message and force push again? anything else on my side?)

**Pull request closed without merging**
