### PR TITLE
 sparse checkout: fix a few bugs and check argument validity for set/add

### PR DESCRIPTION
**Pull request by newren**
== Maintainer notes ==

Note: There is a small textual and small semantic conflict with ds/sparse-checkout-requires-per-worktree-config in seen.  I included the diff with the correct resolution near the end of this cover letter.  If you'd prefer I rebased on top of ds/sparse-chckout-requires-per-worktree-config, let me know.

== Overview ==

This series continues attempts to make sparse-checkouts more user friendly.  A quick overview:
  * Patches 1-2 fix existing bugs from en/sparse-checkout-set (i.e. in v2.35.0)
  * Patch 3 fixes sparse-checkout-from-subdirectories-ignores-"prefix" (see https://lore.kernel.org/git/29f0410e-6dfa-2e86-394d-b1fb735e7608@gmail.com/), in cone mode.  Since we'll get nasty surprises whether we use or don't use "prefix" for non-cone mode, simply throw an error if set/add subcommands of sparse-checkout are run from a subdirectory.
  * Patches 4-5 check positional arguments to set/add and provide errors/warnings for very likely mistakes.  It also adds a --skip-checks flag for overridding in case you have a very unusual situation.

== Update history ==

Changes since v4:
  * have --skip-checks enable running from a subdirectory in non-cone mode
  * make sure new die() messages are marked for translation (and using single quotes instead of double)

Changes since v3:
  * Use strpbrk() instead of multiple strchr(), fix commit message relative to backslashes.

Changes since v2:
  * Dropped patch 5
  * Added Stolee's Reviewed-by

Changes since v1:
  * Dropped the commit changing cone-mode to default (patch 7, which will be split into multiple patches and submitted as a separate series)
  * Removed the RFC label
  * Decided to error out when running set/add with paths from a subdirectory in non-cone mode, and added tests
  * Changed the warning for non-cone mode with individual files to point out that the user is likely trying to select an individual file, but should likely add a leading slash to ensure that is what happens
  * Fixed typos, removed unnecessary condition checks

== Conflict resolution ==

Patch to resolve textual and semantic conflict with ds/sparse-checkout-requires-per-worktree-config:
```
diff --git a/t/t1091-sparse-checkout-builtin.sh b/t/t1091-sparse-checkout-builtin.sh
remerge CONFLICT (content): Merge conflict in t/t1091-sparse-checkout-builtin.sh
index 3c6adeb885..3a95d2996d 100755
--- a/t/t1091-sparse-checkout-builtin.sh
+++ b/t/t1091-sparse-checkout-builtin.sh
@@ -275,24 +275,8 @@ test_expect_success 'sparse-index enabled and disabled' '
 	diff -u sparse full | tail -n +3 >actual &&
 	test_cmp expect actual &&
 
-<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< 286c22e5ec (sparse-checkout: reject arguments in cone-mode that look like patterns)
 	git -C repo config --list >config &&
-	! grep index.sparse config
-|||||||||||||||||||||||||||||||| 89bece5c8c
-		diff -u sparse full | tail -n +3 >actual &&
-		test_cmp expect actual &&
-
-		git -C repo config --list >config &&
-		! grep index.sparse config
-	)
-================================
-		diff -u sparse full | tail -n +3 >actual &&
-		test_cmp expect actual &&
-
-		git -C repo config --list >config &&
-		test_cmp_config -C repo false index.sparse
-	)
->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> 3ce1138272 (config: make git_configset_get_string_tmp() private)
+	test_cmp_config -C repo false index.sparse
 '
 
 test_expect_success 'cone mode: init and set' '
@@ -532,6 +516,7 @@ test_expect_success 'reapply can handle config options' '
 	cat >expect <<-\EOF &&
 	core.sparsecheckout=true
 	core.sparsecheckoutcone=true
+	index.sparse=false
 	EOF
 	test_cmp expect actual &&
 
@@ -539,6 +524,8 @@ test_expect_success 'reapply can handle config options' '
 	git -C repo config --worktree --list >actual &&
 	cat >expect <<-\EOF &&
 	core.sparsecheckout=true
+	core.sparsecheckoutcone=false
+	index.sparse=false
 	EOF
 	test_cmp expect actual &&
```

== CCs ==

cc: Victoria Dye <vdye@github.com>
cc: Derrick Stolee <stolee@gmail.com>
cc: Lessley Dennington <lessleydennington@gmail.com>
cc: Derrick Stolee <derrickstolee@github.com>
cc: Elijah Newren <newren@gmail.com>
cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>

### CODE REVIEW

**Comment by newren** [comment]
@dscho: Any idea why it's failing to submit?

**Comment by dscho** [comment]
Huh. Let me have a look.

**Comment by dscho** [comment]
Oh, I think I know what it is... a recent refactoring seems to have introduced a bug.

**Comment by dscho** [comment]
Let's see whether https://github.com/gitgitgadget/gitgitgadget/commit/eeb49e039b7360232309352027f48dab645891a7 fixes it... [The build is running](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=128433&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=fd9d79e0-dc99-51c0-4ec1-8ae1b7984af2)...

**Comment by dscho** [comment]
@newren 😅 it worked! Sorry for the woes.

**Comment by newren** [comment]
> @newren sweat_smile it worked! Sorry for the woes.

No worries; thanks for the fix, and for the awesome work on gitgitgadget!

**Pull request closed without merging**
