### PR TITLE
Consolidate reachability logic

### PR DESCRIPTION
**Pull request by derrickstolee**
There are many places in Git that use a commit walk to determine
reachability between commits and/or refs. A lot of this logic is
duplicated.

I wanted to achieve the following:

1. Consolidate several different commit walks into one file
2. Reduce duplicate reachability logic
3. Increase testability (correctness and performance)
4. Improve performance of reachability queries

My approach is mostly in three parts:

  I. Move code to a new commit-reach.c file.
 II. Add a 'test-tool reach' command to test these methods directly.
III. Modify the logic by improving performance and calling methods with
     similar logic but different prototypes.

The 'test-tool reach' command is helpful to make sure I don't break
anything as I change the logic, but also so I can test methods that are
normally only exposed by other more complicated commands. For instance,
ref_newer() is part of 'git push -f' and ok_to_give_up() is buried deep
within fetch negotiation. Both of these methods have some problematic
performance issues that are corrected by this series. As I discovered
them, it was clear that it would be better to consolidate walk logic
instead of discovering a new walk in another file hidden somewhere.

For the ok_to_give_up() method, I refactored the method so I could pull
the logic out of the depths of fetch negotiation. In the commit
"commit-reach: make can_all_from_reach... linear" I discuss how the
existing algorithm is quadratic and how we can make it linear. Also, we
can use heuristic knowledge about the shape of the commit graph and the
usual haves/wants to get some extra performance bonus. (The heuristic is
to do a DFS with first-parents first, and stop on first found result. We
expect haves/wants to include ref tips, which typically have their
previous values in their first-parent history.)

One major difference in this series versus the RFC is that I added a new
method 'generation_numbers_enabled()' to detect if we have a commit-graph
file with non-zero generation numbers. Using can_all_from_reach in
is_descendant_of is only faster if we have generation numbers as a cutoff.

V2 Update: The biggest material change in this version is that we drop the
method declarations from commit.h, which requires adding a lot of references
to commit-reach.h across the codebase. This change is in a commit on its own.
In addition, we have the following style-based cleanups:

* Use 'unsigned int' for the flag variables.

* Properly align the here-doc test input data.

* Use singe rev-parse commands in test output, and pipe the OIDs through 'sort'

* Check output of parse_commit()

* Update flag documentation in object.h

* Add tests for commit_contains() including both algorithms.

* Reduce size of "mixed-mode" commit-graph to ensure we start commit walks
  'above' the graph and then walk into the commits with generation numbers.

Thanks,
-Stolee

This series is based on jt/commit-graph-per-object-store

Cc: sbeller@google.com
Cc: jonathantanmy@google.com

### CODE REVIEW

**Comment by dscho** [comment]
So the build & test failed... but it is in the submodule code!

*clicketyclick*

Ah! You target `pu`, which is currently broken: https://git-for-windows.visualstudio.com/git/git%20Team/_build/results?buildId=12365&view=logs (same issue, so it is not your patch series' fault).

**Comment by dscho** [comment]
@derrickstolee Maybe we need to mirror the branches from https://github.com/gitster/git here, so that you can target the correct branch in `pu`? It just causes too much pain, obviously, to base your branch on top of `pu`.

Of course, you could also rebase your branch on top of the respective branch instead of `pu`...

**Comment by derrickstolee** [comment]
@dscho It would be good to be able to declare my "base" branches, so I can target them for the PR builds. I usually track my branches as `topic/base` and `topic/upstream` so I can quickly rebase.

In addition to the volatility of working against 'pu' for build stability, we also have the problem of sending a new version after your series is tracked in 'pu': you'll conflict with your old commits!

**Comment by derrickstolee** [comment]
Because of #25, my v2 is not sent via this PR. This means another submission would collide in version numbers. I'll continue this series using `git send-email`.

**Comment by dscho** [comment]
> It would be good to be able to declare my "base" branches, so I can target them for the PR builds.

FWIW there is now an automated job in place that mirrors all of the branches from gitster/git into this repository, so you will be able to target those branches in the future.

**Pull request closed without merging**
