### PR TITLE
git gui: improve German translation

### PR DESCRIPTION
**Pull request by cstim**
git-gui: update/improve German translation

Update translation template and translation glossary as prerequisite. Then, update German translation (glossary and final translation) to recent source code changes, but also switch several terms from uncommon translations back to English vocabulary, similar to the rest of git-core.

This most prominently concerns "commit" (noun, verb), "repository", "branch", and some more. These uncommon translations have been introduced long ago and never been changed since. In fact, the whole German translation here hasn't been touched for a long time. However, in German literature and magazines, git-gui is regularly noted for its uncommon choice of translated vocabulary. This somewhat distracts from the actual benefits of this tool. So it is probably better to abandon the uncommon translations and rather stick to the common English vocabulary in git version control.

The glossary is adapted to the git-core glossary at 
https://github.com/ruester/git-po-de/wiki/Translation-Guidelines
and the changed and updated terms are used in the actual translation accordingly.

Changes since v1:
- commit message titles with proper capitalization
- commit message includes reason for why German wording has been changed
- changes in German translation are squashed into one commit
- some more wording changes have been integrated after discussion with other German git translators

### CODE REVIEW

**Comment by prati0100** [comment]
Hi @cstim,

Thanks for the contribution. Since I don't speak German, I can't really review the second patch. So unless someone else volunteers to go through it, I'll just trust you and merge it in.

I glanced at the first patch, and I might have a couple comments. I give it a thorough read once you submit it to the list.

Once you feel the two patches are ready, please comment with `/submit` to send them to the Git mailing list for review. The automated message by GitGitGadget has more details of course.

**Comment by cstim** [comment]
Hi @prati0100 , thanks for the heads-up. I got some first feedback from the other German translators. I would like to collect some more feedback from the other German translators, and then submit a consolidated patch. This might take a few more days. Thanks!

**Comment by cstim** [comment]
Dear @prati0100, I have questions to your remark about my first patch:

> I glanced at the first patch, and I might have a couple comments. I will give it a thorough read once you submit it to the list.

The first of my patches was "only" an update of my language's de.po files from the current source code base. As both .pot files were heavily out of date, I regenerated those (`rm po/git-gui.pot; make po/git-gui.pot`), then merged them with the existing po file (`cd po; msgmerge de.po git-gui.pot -o tmp ; mv tmp de.po`). Nothing more than that. This step can of course be done for all other languages just as well. Are you interested in further discussing such a step? I have some background in handling those translation processes, so feel free to discuss those as well.

For my German language patch I made sure to keep this rather technical first step separated from the actual translation update (currently the second patch, more might come within the next days), because the actual translation should get some review from other German speaking translators. One of them already agreed to give a review once I submit this to the git mailing list, but I'd like to do further work before doing so. Thanks!

**Comment by prati0100** [comment]
My comment was mainly about the commit message not following the project's convention. The commit subject should start with 'git-gui: ' and follow with short title that shouldn't need more than one line. I didn't look very closely at the patch contents, but nothing looks out of place to me at first glance.

> One of them already agreed to give a review once I submit this to the git mailing list, but I'd like to do further work before doing so.

Sure, take your time :-). Thanks for contributing.

**Comment by dscho** [comment]
@cstim would you mind changing the upper-case "U" to a lower-case "u" in "git-gui: update German translation."? And while at it, drop the "." at the end?

Thank you!

**Comment by cstim** [comment]
Oops, did I crash the other build pipeline by removing one of my earlier comments here? I thought my comment containing the `/preview` command wasn't needed in the future, so I removed it. Maybe this confused your build automation. Sorry for that.

**Pull request closed without merging**
