### PR TITLE
Makefile: suppress macOS deprecation warning

### PR DESCRIPTION
**Pull request by stefansundin**
cc: Bagas Sanjaya <bagasdotme@gmail.com>

### CODE REVIEW

**Comment by stefansundin** [comment]
I found a tiny grammatical error in my commit message (`deprecation warnings` should be singular). Before I fix that, does anyone have any other comments?

Thanks!

**Comment by jeffhostetler** [comment]
I'm going to look into fixing the code to not used the deprecated routine.

**Pull request closed without merging**
