### PR TITLE
[Outreachy] Move doc to header files

### PR DESCRIPTION
**Pull request by HebaWaly**
Move the documentation from Documentation/technical/api-*.txt to the 
corresponding header file, as it's easier for the developers to find the
usage information beside the code instead of looking for it in another
doc file.

Also documentation/technical/api-*.txt is removed because the 
information it has is will be redundant and it'll be hard to keep it up to
date and synchronized with the documentation in the header files.

api-trace2.txt is not removed because it has lots of valuable information that seems more appropriate to be in a separate doc file not in the trace2.h although the functions documentation is moved to the trace2.h

api-error-handling.txt is not removed as well because no other file seemed to be more suitable for the doc it contains. I'm open to suggestions though.

The ll-merge related doc was removed from api-merge.txt to ll-merge.h, while the rest of the file is left as is.

Signed-off-by: Heba Waly heba.waly@gmail.com

### CODE REVIEW

**Comment by dscho** [comment]
@HebaWaly what is the status of this PR? Can it be closed?

**Comment by HebaWaly** [comment]
> @HebaWaly what is the status of this PR? Can it be closed?

Yes, it should be in master. 
Will close it, thanks

**Pull request closed without merging**
