### PR TITLE
Finish converting `git bisect` into a built-in

### PR DESCRIPTION
**Pull request by dscho**
After three GSoC/Outreachy students spent an incredible effort on this, it is finally time to put a neat little bow on it, or maybe more like a big bow, maybe even a very large one, seeing as it takes quite a while to tie (half a year at the time of writing)...

Changes since v5:
- Fixed the commit message of "bisect run: fix the error message" that had become stale as of v3 due to 80c2e9657f2 "overtaking" it and doing half of its job.
- Skipped translation usage strings in "bisect--helper: migrate to OPT_SUBCOMMAND()" that do not contain translatable parts.
- Minor white-space clean-up in "bisect--helper: migrate to OPT_SUBCOMMAND()".

Changes since v4:
- rebased onto `sg/parse-options-subcommand`
- migrated to `OPT_SUBCOMMAND()`.
- As a consequence, this patch series is now unfortunately very large. And the range-diff is much less useful than I'd like because of the extensive changes that were de facto made a precondition to moving this patch series further. Junio, I would have liked to keep the scope (and burden for the reviewers) substantially smaller, maybe you can help with the review?

Changes since v3:
- Rebased because of merge conflicts with `ab/plug-leak-in-revisions`.
- Fixed the bug that `git bisect --bisect-terms 1 2` wanted to auto-start a bisection if running with a `git` executable built at the in-between state at patch "bisect: move even the command-line parsing to `bisect--helper`". Since this bug was "fixed" in v3 by the very next patch,  "bisect: teach the `bisect--helper` command to show the correct usage strings", v4 avoids introducing this bug simply by letting these two patches trade places. The range-diff admittedly looks quite awful because both patches overlap quite a bit in the lines they modify. The end result is the same, though, the diff between v3's and v4's `builtin/bisect.c` would be empty if I hadn't been forced to rebase.
- Added a test case to ensure that this bug won't be introduced again. This test case is the only _actual_ difference relative to v3 of this patch series.

Changes since v2:
- We're now careful to provide identical usage strings upon `git bisect -h` and `git bisect bogus`.
- When a bogus command is provided, we now error out instead of trying to start a `git bisect` run.
- Rebased onto `main` to avoid plenty of merge conflicts with `rs/bisect-executable-not-found`, `ac/usage-string-fixups` and with `cd/bisect-messages-from-pre-flight-states`.

Changes since v1:

- Added a regression test to "bisect run: fix the error message".
- Added a patch to address an error message that double-single-quoted the command.
- Reworked the logic in "bisect--helper: make `--bisect-state` optional" to delay showing the usage upon an unknown command, which should make the code a lot less confusing.
- Split out the change that moved the `BISECT_STATE` case to the end of the `switch` block.
- Added a patch that replaces the `return error()` calls in `cmd_bisect_helper()` with `die()` calls, to avoid returning -1 as an exit code.
- Dropped the use of `parse_options()` for the single purpose of handling `-h`; This is now done explicitly.
- Simplified the diff of "bisect: move even the option parsing to bisect--helper" by modifying `argc` and `argv` instead of modifying all the function calls using those variables.
- In the "Turn `git bisect` into a full built-in" patch, changed the name of the variable holding the usage to use the `builtin_` prefix used in other built-ins, too.
- Removed the trailing dot from the commit message of "Turn `git bisect` into a full built-in".

Cc: Pranit Bauva <pranit.bauva@gmail.com>
Cc: Tanushree Tumane <tanushreetumane@gmail.com>
Cc: Miriam Rubio <mirucam@gmail.com>
cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Elijah Newren <newren@gmail.com>
cc: Bagas Sanjaya <bagasdotme@gmail.com>
Cc: Junio C Hamano <gitster@pobox.com>

### CODE REVIEW

**Comment by OrToR-KJM** [comment]
내 Galaxy에서 보냄
-------- 원본 이메일 --------발신: "gitgitgadget[bot]" ***@***.***> 날짜: 22/5/17  14:42  (GMT+09:00) 받은 사람: gitgitgadget/git ***@***.***> 참조: Subscribed ***@***.***> 제목: Re: [gitgitgadget/git] Finish converting `git bisect` into a built-in
  (PR #1132) 
There was a status update in the "Stalled" section about the branch js/bisect-in-c on the Git mailing list:
Final bits of "git bisect.sh" have been rewritten in C.

Expecting a reroll.
cf. ***@***.***>
source: ***@***.***>

**Comment by dscho** [comment]
Wow. After almost 11 months, most of the time in "needs review" or in "stalled because of some non-actionable feedback" or in "needs adjusting to patch series that knowingly conflict with this in-flight patch series" state, my time has retroactively been completely wasted by fc304fb52f9d.

**Pull request closed without merging**
