### PR TITLE
Travis CI: Lint for Python syntax errors and undefined names

### PR DESCRIPTION
**Pull request by cclauss**
Several things were changed between Python 2 and Python 3.
Here we are making changes to make the code run on both Py2 and Py3.
We are doing this because the end of life of Python 2 is in 167 days.
We are using __print()__ function because legacy print statements are syntax
errors on Py3.
__reduce()__ was moved in Python 3 and __raw_input()__ was removed so we
make changes to avoid NameErrors at runtime.
Signed-off-by: Christian Clauss <cclauss@me.com>

### CODE REVIEW

**Comment by dscho** [comment]
@cclauss what GitGitGadget wants is that your GitHub profile mentions your clear name... It needs that so that it can construct a sender name for the cover letter.

**Comment by cclauss** [comment]
Yes.  I edited that parameter on GitHub settings and resubmitted.  That seems to have done the trick.  Thanks for your help.  🤞

**Comment by cclauss** [comment]
Did this get to the other side?

$ __git send-email --in-reply-to=xmqqmuh9vmfa.fsf@gitster-ct.c.googlers.com --to=gitster@pobox.com --cc=cclauss@me.com --cc=git@vger.kernel.org --cc=gitgitgadget@gmail.com ./note_to_git.txt__
```
OK. Log says:
Sendmail: /usr/sbin/sendmail -i gitster@pobox.com cclauss@me.com git@vger.kernel.org gitgitgadget@gmail.com
From: cclauss <cclauss@me.com>
To: gitster@pobox.com
Cc: cclauss@me.com,
	git@vger.kernel.org,
	gitgitgadget@gmail.com
Subject: On Python 3 pull request
Date: Fri, 19 Jul 2019 23:19:25 +0200
Message-Id: <20190719211925.16849-1-cclauss@me.com>
X-Mailer: git-send-email 2.22.0
In-Reply-To: <xmqqmuh9vmfa.fsf@gitster-ct.c.googlers.com>
References: <xmqqmuh9vmfa.fsf@gitster-ct.c.googlers.com>
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit

Result: OK
```

**Comment by cclauss** [comment]
$ __cat ./note_to_git.txt__
```
Subject: On Python 3 pull request
Hello Junio C Hamano,

  Thanks for your kind words.  Also thanks for modifying the signature
line to match the cover letter.  That is the correct edit to make.
I also agree with your rewording on print() and reduce().  However, on
input(), I must point out that python-future.org is assuming the
addition of a new dependency (pip install future).  Given the universal
deployment of git, I have chosen not to add a new production dependency
in this case.  We will do it the old fashioned way via try/except.

    - Use `input()` on Python 3 and `raw_input()` on Python 2 because
      they provide equivalent functionality.

On the flake8 test selection, this PR does _not_ focus on "_style
violations_" (the majority of flake8 error codes that
[__python/black__](https://github.com/python/black) can autocorrect).
Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8
can not build an Abstract Syntax Tree (AST).  Often these issues are a
sign of unused code or code that has not been ported to Python 3.
 These would be compile-time errors in a compiled language but in a
dynamic language like Python they result in the script halting/crashing
on the user.
* F63 tests are usually about the confusion between identity and
equality in Python.  Use ==/!= to compare str, bytes, and int literals
is the classic case.  These are areas where __a == b__ is True but
__a is b__ is False (or vice versa).
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a
sign of a typo, missing imports, or code that has not been ported to
Python 3.  These also would be compile-time errors in a compiled
language but in Python a __NameError__ is raised which will halt/crash
the script on the user.

On sustained maintenance of the flake8 tests, flake8 is an Open Source
project like git is so I can not make any guarantees that future
changes will not be made in that codebase,  However, flake8  is a very
stable project which is broadly used so these codes should continue to
run the same tests.  As discussed above, these tests have been
carefully selected to find only "show stopper" errors that effect
runtime safety or program correctness.  We are not enabling many
flake8 errors codes: https://lintlyci.github.io/Flake8Rules

Given all of this, is this pull request OK in its current form or does
the content or commit message need to be modified?
```

**Comment by dscho** [comment]
> Did this get to the other side?

I don't think it did, given the thread at https://public-inbox.org/git/pull.290.git.gitgitgadget@gmail.com/#r.

My _guess_ is that the `note_to_git.txt` file did not look enough like an mbox... It should probably look more like the output of `git -p format-patch --stdout -1`, in particular the empty line between the header and the body. I think.

**Comment by cclauss** [comment]
The F63 instances will raise SyntaxWarnings on Python >= 3.8 so it is best to fix them now. https://docs.python.org/3.8/whatsnew/3.8.html#porting-to-python-3-8

**Comment by dscho** [comment]
Whoa. I think GitGitGadget mistook a related patch for superseding this here PR.

@cclauss would you mind rebasing and re-submitting?

**Comment by dscho** [comment]
I guess I cannot re-open... My advice to rebase and re-submit still stands, although this should be submitted as a fresh, new GitGitGadget PR, I guess...

**Pull request closed without merging**
