### PR TITLE
Sparse Index: Integrate with 'git add'

### PR DESCRIPTION
**Pull request by derrickstolee**
This patch series re-submits the 'git add' integration with sparse-index. The performance gains are the same as before.

It is based on ds/commit-and-checkout-with-sparse-index.

This series was delayed from its initial submission for a couple reasons.

The first was because it was colliding with some changes in mt/add-rm-in-sparse-checkout, so now we are far enough along that that branch is in our history and we can work forwards.

The other concern was about how 'git add <path>' should respond when a path outside of the sparse-checkout cone exists. One recommendation (that I am failing to find a link to the message, sorry) was to disallow adding files that would become index entries with SKIP_WORKTREE on. However, as I worked towards that goal I found that change would cause problems for a realistic scenario: merge conflicts outside of the sparse-checkout cone.

*Update:* Elijah points out that the SKIP_WORKTREE bit is removed from conflict files, which allows adding the conflicted files without warning. (However, we also need to be careful about untracked files, as documented in the test added here.)

The first patch of this series adds tests that create merge conflicts outside of the sparse cone and then presents different ways a user could resolve the situation. We want all of them to be feasible, and this includes:

1. Reverting the file to a known version in history.
2. Adding the file with its contents on disk.
3. Moving the file to a new location in the sparse directory.

The one place I did continue to update is 'git add --refresh <path>' to match the behavior added by mt/add-rm-in-sparse-checkout which outputs an error message. This happens even when the file exists in the working directory, but that seems appropriate enough.

Updates in V3
---------------

* Added disclaimer to the merge-conflict test that this is documenting current behavior, not endorsing it.

* Added Elijah's reviewed-by. Thanks for the review!

Thanks,
-Stolee

cc: gitster@pobox.com
cc: newren@gmail.com
cc: matheus.bernardino@usp.br
cc: stolee@gmail.com
cc: Eric Sunshine <sunshine@sunshineco.com>

### CODE REVIEW

**Comment by derrickstolee** [comment]
> This patch series was integrated into maint via [git@8e97852](https://github.com/git/git/commit/8e97852919fa422bc5fe57bc7e71826cf2b5224d).

@dscho was this a GGG bug or did Junio accidentally push the wrong branches?

**Comment by dscho** [comment]
> 
> 
> > This patch series was integrated into maint via [git@8e97852](https://github.com/git/git/commit/8e97852919fa422bc5fe57bc7e71826cf2b5224d).
> 
> @dscho was this a GGG bug or did Junio accidentally push the wrong branches?

That looks very much like a GitGitGadget bug. I had a look and the `upstream/maint` branch was most recently updated 7 weeks ago.

*clicketyclick*

And yes, I can reproduce in my local `gitgitgadget/gitgitgadget` checkout:

```console
$ ts-node script/misc-helper.ts identify-merge-commit maint 4589bca829a2ace58bc98876cccd7dbd2e89f732
8e97852919fa422bc5fe57bc7e71826cf2b5224d
```

**Comment by dscho** [comment]
> ```
> $ ts-node script/misc-helper.ts identify-merge-commit maint 4589bca829a2ace58bc98876cccd7dbd2e89f732
> 8e97852919fa422bc5fe57bc7e71826cf2b5224d
> ```

Sorry, that's the wrong incantation. GitGitGadget identified 54beed24d22867a98fc247e1031e3486573f1553 as the tip commit in upstream, which is obviously wrong... That's why it closed it by mistake.

I have no idea how that mis-identification happened, and hope that my manual fix (5c7a5aae2777a53106d77c1f08e9ec49e5c0f4c1) won't be overwritten later.

**Comment by derrickstolee** [comment]
This merged to `next`.

**Pull request closed without merging**
