### PR TITLE
[RFC] contrib/credential/osxkeychain: store new attributes

### PR DESCRIPTION
**Pull request by hickford**
Is any keen MacOS user interested in building and testing this RFC patch? I personally don't have a MacOS machine, so haven't tried building it. Fixes are surely necessary. Once it builds, you can test the feature with:

    GIT_TEST_CREDENTIAL_HELPER=osxkeychain ./t0303-credential-external.sh

The feature would help git-credential-oauth users on MacOS https://github.com/hickford/git-credential-oauth/issues/42

### CODE REVIEW

**Comment by Bo98** [comment]
This is quite the coincidence given I had also yesterday worked on osxkeychain updates: https://github.com/Bo98/git/commits/osxkeychain-update, though with a much larger scope of fixing osxkeychain failing several parts of the test suite and updating the code to not use macOS keychain APIs that were deprecated 10 years ago (particularly given osxkeychain requires 10.7 and the "new" API is available since 10.6).

Though I haven't contributed to Git before myself, so wasn't sure how far it would go.

**Comment by hickford** [comment]
> quite the coincidence ... much larger scope https://github.com/git/git/compare/master...Bo98:git:osxkeychain-update

@Bo98 Fancy that! Great work. Assuming it builds without warnings and the tests pass, that looks ready to submit to the mailing list.

I'll close this PR.

**Pull request closed without merging**
