### PR TITLE
ci: update Cirrus-CI image to FreeBSD 13.0

### PR DESCRIPTION
**Pull request by phil-blain**
Here is a proper patch following my earlier mail  [1].

[1] https://lore.kernel.org/git/CAPUEspgdAos4KC-3AwYDd5p+u0hGk73nGocBTFFSR7VB9+M5jw@mail.gmail.com/T/#t

CC: Carlo Marcelo Arenas Belón <carenas@gmail.com>
CC: Ed Maste <emaste@FreeBSD.org>

### CODE REVIEW

**Comment by phil-blain** [comment]
OK, thanks for confirming. I just checked the code and it seems that it only allows long URLs (i.e. anything that does not have spaces in the first 10 chars...)

**Comment by dscho** [comment]
> OK, thanks for confirming. I just checked the code and it seems that it only allows long URLs (i.e. anything that does not have spaces in the first 10 chars...)

It should be easy to extend to exempt any line starting with white-space.

**Comment by phil-blain** [comment]
> > OK, thanks for confirming. I just checked the code and it seems that it only allows long URLs (i.e. anything that does not have spaces in the first 10 chars...)
> 
> It should be easy to extend to exempt any line starting with white-space.

it was indeed pretty easy: https://github.com/gitgitgadget/gitgitgadget/pull/993

**Comment by phil-blain** [comment]
merged to `master` in a9e7c3a6ef

**Pull request closed without merging**
