### PR TITLE
update-index: refresh should rewrite index in case of racy timestamps

### PR DESCRIPTION
**Pull request by mstrap**
This patch makes update-index --refresh write the index if it contains racy timestamps, as discussed at [1].

Changes since v3:
* test-lib: improve API for verifying file mtime
  * fix quoting around "$1"
  * use "rm -f" for cleanup of auxiliary files
  * improve API description comments
* Note that gitgitgadget's "freebsd_12" check is failing since a couple of days (unrelated to this pull request); hence, this check hasn't been applied to this patch series

Changes since v2:
* new patch: test-lib: introduce API for verifying file mtime
* new patch: t7508: fix bogus mtime verification for test
  "--no-optional-locks prevents index update"
* change new tests in t2108 and t7508 to use new test-lib mtime API
* fix "--refresh has no racy timestamps to fix" to use +60s mtime to be save on VFAT

Changes since v1:
* main commit message now uses 'git update-index' and the paragraph was dropped
* t/t7508-status.sh: two tests added which capture status racy handling 
* builtin/update-index.c: comment improved
* t/t2108-update-index-refresh-racy.sh: major overhaul
  * one test case added
  * mtime-manipulations simplified and aligned to t7508
  * code style fixes, as discussed

[1] https://lore.kernel.org/git/d3dd805c-7c1d-30a9-6574-a7bfcb7fc013@syntevo.com/

### CODE REVIEW

**Comment by mstrap** [comment]
@bk2204 may I ask you to /allow me?

**Comment by dscho** [comment]
@mstrap please edit the PR description, it will be sent as a "cover letter" (and therefore does not need to repeat the commit message, and also does not need a sign-off). Thank you!

**Pull request closed without merging**
