### PR TITLE
(fix): make all die() error messages lowercase

### PR DESCRIPTION
**Pull request by EthanDevelops**
Related issues:
https://github.com/gitgitgadget/git/issues/635

The Git suite CodingGuidelines suggest [this](https://github.com/git/git/blob/v2.26.2/Documentation/CodingGuidelines#L496) about Error messages:

> Error Messages
> 
> - Do not end error messages with a full stop.
> 
> - Do not capitalize ("unable to open %s", not "Unable to open %s")

This fixes the die() error messages so they follow this guideline.

Signed-off-by: EthanDevelops <git@ethanlibs.co>

### CODE REVIEW

**Comment by EthanDevelops** [comment]
Why did the tests fail?

**Comment by derrickstolee** [comment]
@EthanDevelops: You will likely want to expand your commit message, but also your authorship and sign-off should be a real email address, not the GitHub default user email address.

**Pull request closed without merging**
