### PR TITLE
setup: fix function name

### PR DESCRIPTION
**Pull request by clebergnu**

### CODE REVIEW

**Comment by dscho** [comment]
Interesting find. I am curious: how did you stumble over this? Did you hit that bug?

**Comment by clebergnu** [comment]
> Interesting find. I am curious: how did you stumble over this? Did you hit that bug?

I stumbled over this while following the behavior of `git config` on "unsafe" repositories.  I have a pet peeve with the current error message being given on `git config --local` on an unsafe repository:

```
$ ~/src/git/git-config --local user.email "foo@bar.com"
fatal: --local can only be used inside a git repository
```

And I'm looking into making the message the same one would get with other git commands:

```
$ ~/src/git/git-rev-parse HEAD
fatal: unsafe repository ('/tmp/t3' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /tmp/t3
```

I just thought I'd get the "first time contributor" out of the way before sending that other work.

**Comment by clebergnu** [comment]
@dscho since I got your attention, would it possible for you to review the patch on the ML? Thanks a lot!

**Pull request closed without merging**
