### PR TITLE
INSTALL: use '$', not '#' for user-run command prompt

### PR DESCRIPTION
**Pull request by sunshaoce**
The user prompt should be `$` instead of `#`.

cc: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Philippe Blain <levraiphilippeblain@gmail.com>
cc: Christian Couder <christian.couder@gmail.com>

### CODE REVIEW

**Comment by sunshaoce** [comment]
Thanks everyone! I’ll close the PR.

**Comment by dscho** [comment]
> Thanks everyone! I’ll close the PR.

@sunshaoce Could you please reply via mail to https://lore.kernel.org/git/pull.1241.git.1653424998869.gitgitgadget@gmail.com as indicated in https://github.com/gitgitgadget/gitgitgadget/wiki/ReplyToThis, as most Git developers only look at the Git mailing list? Thank you.

**Pull request closed without merging**
