### PR TITLE
t/lib-credential: clean additional credential

### PR DESCRIPTION
**Pull request by Bo98**
cc: Jeff King <peff@peff.net>

### CODE REVIEW

**Comment by hickford** [comment]
This looks ready to submit to the mailing list.

The failed test looks flaky rather than indicative of a problem. If you're concerned, one way to rerun it is to rebase and force push.

**Comment by Bo98** [comment]
> This looks ready to submit to the mailing list.

Will need an `/allow` to be able to do that.

> The failed test looks flaky rather than indicative of a problem. If you're concerned, one way to rerun it is to rebase and force push.

Agreed. Not particularly concerned but will rebase anyway.

**Pull request closed without merging**
