### PR TITLE
Improve rebase empty commit advice

### PR DESCRIPTION
**Pull request by phillipwood**
This is a reroll of js/advise-rebase-skip[1]. I've added some more commits to improve the test coverage and handle edit & reword as well as pick commands. I've also changed the advice printed by an empty cherry-pick performed during a rebase to be the same whether it is part of a sequence of cherry-picks or just a single pick. 

There are a couple of RFC patches at the end that change the advice for fixups that empty HEAD and change the handling of CHERRY_PICK_HEAD so if a user commits a conflict resolution the authorship is preserved.

These patches are based on a merge of ra/cherry-pick-revert-skip and pw/sequencer-compare-with-right-parent-to-check-empty-commits

[1] https://lore.kernel.org/git/<pull.417.git.1571787022.gitgitgadget@gmail.com>

Cc: Johannes Schindelin <johannes.schindelin@gmx.de>
Based-on: d5e6c1deff

### CODE REVIEW

**Comment by phillipwood** [comment]
@dscho how do I tell gitgitgadet what base to use when sending out patches? - I've added Based-on: but I'm not sure what that is used for

**Comment by dscho** [comment]
> how do I tell gitgitgadet what base to use when sending out patches?

@phillipwood First hit the <kbd>Edit</kbd> button:

image

Then use the drop-down menu to choose a different branch, and click <kbd>Save</kbd>:

image

The base commit must be a branch tip (or the merge base between your branch and the base branch), other base commits are not supported by GitGitGadget.

**Comment by phillipwood** [comment]
> > how do I tell gitgitgadet what base to use when sending out patches?
> The base commit must be a branch tip (or the merge base between your branch and the base branch), other base commits are not supported by GitGitGadget.

@dscho thanks. Oh dear, this is based on a merge of two branches :-(. ra/cherry-pick-revert-skip is in master but if I rebase onto just pw/rebase-empty-commit-advice then I have to add the tests from ra/cherry-pick-revert-skip into this series. I think I'll just use `git send-email`

**Comment by dscho** [comment]
> this is based on a merge of two branches :-(. ra/cherry-pick-revert-skip is in master but if I rebase onto just pw/rebase-empty-commit-advice then I have to add the tests from ra/cherry-pick-revert-skip into this series.

I would have simply used `pu` as base until the time when `pw/rebase-empty-commit-advice` trickled down into `next`, then changed to `next`...

**Pull request closed without merging**
