### PR TITLE
config.txt: add completion for include, includeIf

### PR DESCRIPTION
**Pull request by ziosombrero**
CC: Ævar Arnfjörð Bjarmason <avarab@gmail.com>
cc: Jeff King <peff@peff.net>

Update 2022-07-16: I addressed the suggestions by Jeff King and Junio C. Hamano by integrating their fixes and by rewording the commit message, so that emphasis is put on the documentation enhancement and mentioning the improved tab completion as a beneficial side effect.

cc: Jeff King <peff@peff.net>

### CODE REVIEW

**Comment by ziosombrero** [comment]
@dscho I added my full name to my Github profile, should I submit again to trigger the checks?

**Comment by dscho** [comment]
@ziosombrero you can simply try to `/preview`.

**Comment by dscho** [comment]
@ziosombrero I think it is time to `/submit` now, right?

**Pull request closed without merging**
