### PR TITLE
stash: add reported regression

### PR DESCRIPTION
**Pull request by stefanbeller**
Testing the regression as reported in https://public-inbox.org/git/6e01daf2-5fb7-b6c0-2833-aa696241c609@virtuell-zuhause.de/

### CODE REVIEW

**Comment by dscho** [comment]
@stefanbeller with the checks all passing, does that mean that this is not an issue at all?

**Comment by dscho** [comment]
@stefanbeller I guess we can close this now?

**Comment by stefanbeller** [comment]
@dscho Thanks for cleaning up after me.

**Pull request closed without merging**
