### PR TITLE
Avoid spawning `gzip` in `git archive`

### PR DESCRIPTION
**Pull request by dscho**
When creating `.tar.gz` archives with `git archive`, we let `gzip` handle the compression part. But that is not even necessary, as we *already* require zlib (to compress our loose objects). It is also unfortunate, as it requires `gzip` to be in the `PATH` (which is not the case e.g. with MinGit for Windows, which tries to bundle just the bare minimum of files to make Git work non-interactively, for use with 3rd-party applications requiring Git).

This patch series resolves this conundrum by teaching `git archive` the trick to gzip-compress in-process, and it is based on https://github.com/git-for-windows/git/pull/2077

Changes since v2:
- Added a perf test.
- The change to make `BLOCKSIZE` unsigned was dropped.
- The pseudo command is now called `:internal-gzip:` instead of `:zlib`.
- Integrated a patch using an extra thread for `gzip` compression, based on one of René Scharfe's patches.
- Performed some benchmarking with zlib 1.2.11 and with a zlib version with speed improvements proposed by Intel, and included the results in the added commit's message.

Changes since v1:
* The commit messages were touched up quite a bit.
* There is now a new commit that marks the `BLOCKSIZE` constant as unsigned.
* The first commit used to introduce the `gzip` variable prematurely. This part has been moved into the appropriate commit (which used to be 2/2 and now is 3/4).
* The second commit was split into two: 3/4 which introduces the new `:zlib` pseudo command, and 4/4 that switches the default.
* The `GZIP` prerequisite was dropped from a couple of tests in t5000 that no longer need it.
* The magic `"wb\0"` code was replaced by a `strbuf`-based one.
* The error message was improved when `gzclose()` failed.

Cc: Jeff King <peff@peff.net>, René Scharfe <l.s.r@web.de>, brian m. carlson <sandals@crustytoothpaste.net>

### CODE REVIEW

**Comment by r1walz** [comment]
@dscho I am working on this and will soon submit a patch.

@peff mentioned [here](https://public-inbox.org/git/20190413013451.GB2040@sigill.intra.peff.net/) that it is perfectly fine for `zlib` to declare `gzFile` as a `struct` to fix which, I am thinking of adding a wrapper struct to `gzFile` with one more member as `init`, the value of which will determine whether `gzFile` is initialized. I guess doing this will no longer require the change in code.

He also wrote to declare `BLOCKSIZE` as 'U' in the first place which I think is logical, so I'll incorporate his suggestion in my preparatory step.

**Comment by dscho** [comment]
> I am working on this and will soon submit a patch.

Actually, that surprises me. The deal is: once I send an iteration via GitGitGadget, I will take care of it.

**Comment by dscho** [comment]
> I am thinking of adding a wrapper struct to `gzFile` with one more member as `init`

Why not just make the variable a pointer (i.e. `NULL` by default)?

> He also wrote to declare `BLOCKSIZE` as 'U'

You mean mark the constant as unsigned. Yes, that sounds fine, too.

But the biggest problem is now that we both stumble over each other's toes. I took custody of this patch series in Git for Windows, and upstreamed it via this here PR. Which means I took on the responsibility of taking it from here.

But now you want to take it from there, and you probably want to send the next iteration yourself, doing everything manually because you somehow think that is better than using GitGitGadget. In a sense, it *is* better, because GitGitGadget would not accept a `/submit` from you in this here PR, as *I* opened the PR. GitGitGadget tries to prevent accidental contributions by requiring the same person who opened the PR to submit it.

If you still want to take back ownership of this PR, I will send a reply to the mailing list saying so, and close the PR.

Is that what you want?

**Comment by r1walz** [comment]
> But now you want to take it from there, and you probably want to send the next iteration yourself, doing everything manually because you somehow think that is better than using GitGitGadget.

:laughing: is this sarcasm?

> If you still want to take back ownership of this PR, I will send a reply to the mailing list saying so, and close the PR.

It's fine by me if you are working on it. My examinations are near, so I won't be getting any time to work anyway.
Thanks!

**Comment by r1walz** [comment]
Hi @dscho 

What's the status of the patch? I read the mails but it seems to have stopped receiving the updates. Hope this does not die out. Thanks for working on this and taking this forward.

**Comment by dscho** [comment]
> What's the status of the patch?

I still need to integrate René's patch.

**Comment by dscho** [comment]
Superseded by https://lore.kernel.org/git/217a2f4d-4fc2-aaed-f5c2-1b7e134b046d@web.de/

**Pull request closed without merging**
