### PR TITLE
Inform Users about help.autocorrect

### PR DESCRIPTION
**Pull request by Brian-Bartels**
In a poll of 200 Microsoft employees, 162/200 didn't know about help.autocorrect. It's my favorite git feature and I believe that it could be more advertised to save developers inner loop pain.

### CODE REVIEW

**Comment by Brian-Bartels** [comment]
@phillipwood I need allow permissions, Can you help :) thanks

**Comment by dscho** [comment]
> 
> 
> Also what is wrong with my commit messages?

The requirements are listed here: https://git-scm.com/docs/SubmittingPatches#describe-changes. In the current context:

- The commit message should continue in _lower_ case after the colon in the first line, i.e. "logs: inform [...]" instead of "logs: Inform [...]".
- The maximum line length is 76 columns. Your commit message has a line that is 109 columns long. You would need to add a line break either before or after the word "short".
- The commit needs to be [signed off](https://git-scm.com/docs/SubmittingPatches#sign-off), i.e. there should be a "Signed-off-by: [your name and email]" certifying that you are legally allowed to contribute this under the GPL to the Git project.

In general, it is a good idea to have a look around Git's commits to see how the expected format looks like. You will see that the format is more about explaining the rationale (or, motivation) for the patch, then go into the context that is not readily visible from the patch, and then maybe a discussion of alternative approaches and why they haven't been chosen.

See 12358755949084392b1112cfb5cb4feb9935331f for a good example.

Also note that the reviewers will frown upon _four_ commits change the same line four times. The Git project highly discourages patch series that introduce a problem merely to fix it within the same patch series. You probably want to consider squashing those changes into a single one before going any further.

**Comment by dscho** [comment]
@Brian-Bartels still interested in this PR?

**Comment by Brian-Bartels** [comment]
@dscho honestly no. I've contributed to other OS projects in the past. None have been as closed off and confusing as Git

**Pull request closed without merging**
