### PR TITLE
Psuh Codelab

### PR DESCRIPTION
**Pull request by torquestomp**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

For a single-commit pull request, please *leave the pull request description
empty*: your commit message itself should describe your changes.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by dscho** [comment]
Please use your own fork for practicing how to use GitHub.

**Comment by nasamuffin** [comment]
@dscho Do we want people to be able to /preview changes like this? Or do we want them to only /preview actual changes once they are familiar with the rest of the tutorial? For example, #437 seemed OK, but that was also 5 years ago. What do we want to update the tutorial to suggest instead?

**Comment by dscho** [comment]
> Do we want people to be able to /preview changes like this?

I wonder whether it would make more sense to focus more on making changes that would be acceptable to the Git reviewers first, and only when (if?) that stage is reached, start playing with `/preview`?

**Comment by nasamuffin** [comment]
> > Do we want people to be able to /preview changes like this?
> 
> I wonder whether it would make more sense to focus more on making changes that would be acceptable to the Git reviewers first

That is, "Don't send the commits from this tutorial - instead, consider <pointer to list of ongoing small refactor efforts>, and then send those commits by publishing a PR to git/git"?

I wonder if we have such a list. It seems like a moving target, but for now things that occur to me are:
* parameterize the_repository in more places // remove USE_THE_REPOSITORY_VARIABLE from more .c files
* write unit tests
* improvements to MyFirstContribution

it'd be nice to have these efforts named in some more lively place. Maybe we can chat about it in Berlin next week.

**Comment by dscho** [comment]
> > > Do we want people to be able to /preview changes like this?
> > 
> > 
> > I wonder whether it would make more sense to focus more on making changes that would be acceptable to the Git reviewers first
> 
> That is, "Don't send the commits from this tutorial - instead, consider , and then send those commits by publishing a PR to git/git"?

I'm not sure I understand.

What I am trying to say is that there is little value in pursuing the mastery of the code contribution mechanics if there is no actual code to contribute.



> I wonder if we have such a list.

If you are looking for ideas what to work on, there's nothing official, I don't think. There is https://github.com/gitgitgadget/git/issues, of course, (which some people mistake for an invitation to report bugs), there is https://lore.kernel.org/git/?q=leftoverbits (but that is seriously uncurated, and of course it is tricky to figure out whether any of those are still relevant, at least for people who are interested in their first contribution).

There also used to be something somewhere on https://crbug.com/ but I cannot find it anymore.

**Pull request closed without merging**
