### PR TITLE
Recommend "git gc --auto" instead of "git prune"

### PR DESCRIPTION
**Pull request by johnlinp**
Fix according to #642.

### CODE REVIEW

**Comment by johnlinp** [comment]
Hi all,

gitgitgadget[bot] <notifications@github.com> 於 2020年6月8日 週一 上午4:48寫道：
>
> On the Git mailing list, Denton Liu wrote (reply to this):
>
> Hi all,
>
> On Sun, Jun 07, 2020 at 10:10:19AM -0700, Junio C Hamano wrote:
> > "brian m. carlson" <sandals@crustytoothpaste.net> writes:
> >
> > >> diff --git a/builtin/gc.c b/builtin/gc.c
> > >> index 8e0b9cf41b3..3833a3de332 100644
> > >> --- a/builtin/gc.c
> > >> +++ b/builtin/gc.c
> > >> @@ -692,7 +692,7 @@ int cmd_gc(int argc, const char **argv, const char *prefix)
> > >>
> > >>   if (auto_gc && too_many_loose_objects())
> > >>   warning(_("There are too many unreachable loose objects; "
> > >> - "run 'git prune' to remove them."));
> > >> + "run 'git gc --auto' to remove them."));
> > >
> > > I'm not sure this is correct.  If we have just expelled a large number
> > > of objects from a pack into loose objects because they're no longer
> > > referenced, it's possible we may trigger another git gc --auto on the
> > > next time we run a command.  If so, no amount of git gc --auto is going
> > > to help here; you really have to run git prune.
> >
> > Correct.  When running manually, after noticing the need to do a GC,
> > it is a mental bug to add "--auto" to it, I would think.
>
> Sorry about the confusion, when I was responding to the original
> issue[0], I mistakenly typed the wrong thing. I meant to suggest
> replacing it with `git gc --prune=now`, _not_ `git gc --auto` but I
> guess I had my wires crossed. With this in mind...
>
> The rationale behind this change is that John wanted to add bash
> completions for `git prune`. However, I noted that prune is a plumbing
> command and users should opt to use `git gc` instead. He mentioned that
> sometimes when auto gc runs, it tells the user that they should run
> `git prune` so I suggested (meant to suggest) replacing the command with
> `git gc --prune=now` instead so that users could call the porcelain.
>
> [0]: https://github.com/gitgitgadget/git/issues/642
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you all for helping me clarify the problem. Then I would close
this PR and submit a new PR for replacing the command to `git gc
--prune=now`.

Best,
John Lin

**Comment by johnlinp** [comment]
As we agreed, this is not a correct fix. Closing this PR.

**Comment by johnlinp** [comment]
Hi Junio,

gitgitgadget[bot] <notifications@github.com> 於 2020年6月9日 週二 上午1:38寫道：

>
> On the Git mailing list, Junio C Hamano wrote (reply to this):
>
> Denton Liu <liu.denton@gmail.com> writes:
>
> >> Correct.  When running manually, after noticing the need to do a GC,
> >> it is a mental bug to add "--auto" to it, I would think.
> >
> > Sorry about the confusion, when I was responding to the original
> > issue[0], I mistakenly typed the wrong thing. I meant to suggest
> > replacing it with `git gc --prune=now`, _not_ `git gc --auto` but I
> > guess I had my wires crossed. With this in mind...
> >
> > The rationale behind this change is that John wanted to add bash
> > completions for `git prune`. However, I noted that prune is a plumbing
> > command and users should opt to use `git gc` instead. He mentioned that
> > sometimes when auto gc runs, it tells the user that they should run
> > `git prune` so I suggested (meant to suggest) replacing the command with
> > `git gc --prune=now` instead so that users could call the porcelain.
>
> Nice to know.  The reasoning behind the change should be available
> to those who only look at "git show".
>
> John, if you are to send an updated patch, please make sure you have
> a meaningful log message in it.
>
> Thanks.

Thank you for the kind reminder. I'll try to provide the reasoning
behind this change.

Best,
John Lin

**Comment by dscho** [comment]
@johnlinp please note that Junio cannot see your answer. You need to follow the advice in the "reply to this" link to send a reply via email.

**Comment by johnlinp** [comment]
@dscho Thank you for telling me this. I'm already aware of this problem since @Denton-L told me this at https://github.com/gitgitgadget/git/pull/652#issuecomment-640972012.

**Pull request closed without merging**
