### PR TITLE
ci:  fix the vs-build job so that CI builds pass again

### PR DESCRIPTION
**Pull request by dscho**
This was noticed first in a Git for Windows PR.

### CODE REVIEW

**Comment by SibiSiddharthan** [comment]
@dscho Looks like GitHub has upgraded to CMake v3.19.1. In this version I have upstreamed few changes to CMake that should change the behavior of how libraries are searched(i.e from all directories per name(old way) to all names per directories). So, we don't need to hard code the library names anymore. Even if the runners install new packages there will be no conflict for the libraries we are using.

**Comment by dscho** [comment]
@SibiSiddharthan you mean you got changes accepted into CMake? Congratulations! What do we need to do on Git's side to accommodate?

**Comment by SibiSiddharthan** [comment]
Yes, my changes have been accepted into CMake, and released in version 3.19. 
This particular change(finding libraries) does not require a version bump. (yay!)
You do not need to hard code the libraries `we need currently` anymore in CI script.

**Comment by dscho** [comment]
> You do not need to hard code the libraries `we need currently` anymore in CI script.

I don't understand. Could you elaborate, please?

**Comment by SibiSiddharthan** [comment]
> I don't understand. Could you elaborate, please?

Before this change, we were using `Iconv_INCLUDE_DIR`, `Iconv_LIBRARY ` to point to our iconv. We don't need to do this anymore as `CMAKE_PREFIX_PATH` will suffice.
In the future _if_ git uses say libfoo, and libfoo is not there in the default find_package of CMake, we might need to explicitly specify libfoo

**Pull request closed without merging**
