### PR TITLE
Allow 'reset --quiet' to refresh the index, use 'reset --quiet' in 'stash' 

### PR DESCRIPTION
**Pull request by vdye**
In the process of working on tests for 'git stash' sparse index integration, I found that the '--quiet' option in 'git stash' does not suppress all non-error output when used with '--index'. Specifically, this comes from an invocation of 'git reset' *without* the '--quiet' flag in 'reset_head()'. Upon enabling that flag, though, I discovered that 1) 'reset' does not refresh the index if '--quiet' is specified (as of [1]) and 2) 'git stash' needs the index to be refreshed after the reset. 

This series aims to decouple the "suppress logging" and "skip index refresh" behaviors in 'git reset --mixed', then allow 'stash' to internally use reset with logs suppressed but index refresh enabled. This is accomplished by introducing the '--[no-]refresh' option and 'reset.refresh' config setting to 'git reset'. Additionally, in the spirit of backward-compatibility, '--quiet' and/or 'reset.quiet=true' without any specified "refresh" option/config will continue to skip 'refresh_index(...)'.

There are also some minor updates to the advice that suggests skipping the index refresh:

- replace recommendation to use "--quiet" with "--no-refresh"
- use 'advise()' rather than 'printf()'
- rename the advice config setting from 'advice.resetQuiet' to to 'advice.resetNoRefresh'
- suppress advice if '--quiet' is specified in 'reset'

Finally, tests are added to 't7102-reset.sh' verifying whether index refresh happens when expected and to 't3903-stash.sh' verifying that 'apply --quiet' no longer prints extraneous logs. 

## Changes since V2
- Rename 'test_index_refreshed' to 'test_reset_refreshes_index'
- Move comments explaining the "reset refreshes index" test logic inline with execution
- Replace 'git read-tree' with 'git diff-files' in 'test_reset_refreshes_index' for a (hopefully) more future-proofed command verifying for index refresh
- Add tests for ensuring the index is refreshed after 'git stash push --staged' and 'git stash apply --index'

## Changes since V1
- Update cover letter title
- Squash 't7102' test fixes from patch 5 into patch 2
- Refactor 't7102' tests to properly use inline config settings

[1] https://lore.kernel.org/git/20181023190423.5772-2-peartben@gmail.com/

Thanks! 
-Victoria

CC: derrickstolee@github.com
cc: Phillip Wood <phillip.wood123@gmail.com>

### CODE REVIEW

**Comment by derrickstolee** [comment]
@vdye: just a thought: We could keep the existing behavior if we make `git reset --quiet` imply `--skip-refresh` and have `git stash` use `git reset --quiet --no-skip-refresh`. What do you think about that approach?

**Comment by vdye** [comment]
> @vdye: just a thought: We could keep the existing behavior if we make `git reset --quiet` imply `--skip-refresh` and have `git stash` use `git reset --quiet --no-skip-refresh`. What do you think about that approach?

After opening this, I was thinking along the same lines. I'm planning to look this whole series over again (e.g., to make sure the command line options _actually_ override the config settings), which is why I haven't actually submitted yet. 

As for the suggestion itself, it fortunately looks like there's at least some precedent for a command line option that implies another that can be overridden (`git commit`'s `-z` does: "If no format is given, implies the `--porcelain` output format."). I'm still unhappy with the idea of `--quiet` side-effecting the index, though, so I want to come up with what a clear "deprecation path" might look like before I submit.

**Pull request closed without merging**
