### PR TITLE
Allow disabling advice shown after merge conflicts

### PR DESCRIPTION
**Pull request by phil-blain**
This series introduces a new config 'advice.mergeConflict' and uses it
to allow disabling the advice shown when 'git rebase', 'git cherry-pick',
'git revert', 'git rebase --apply' and 'git am' stop because of conflicts.

Thanks everyone for the reviews!

Changes since v2:
- expanded the commit messages to explain why the tests for 'git rebase'
do not need to be adjusted
- adjusted the wording of the new 'advice.mergeConflict' in the doc, as
suggested by Kristoffer for uniformity with his series which is already
merged to 'master' (b09a8839a4 (Merge branch 'kh/branch-ref-syntax-advice',
2024-03-15)).
- checked all new output manually and consequently adjusted the code in 1/2
to avoid a lonely 'hint: ' line.
- adjusted the addition in advice.h in 1/2 to put the new enum alphabetically,
as noticed by Rubén.
- added misssing newlines in 2/2 as noticed by Phillip and tweaked by Junio.
- rebased on master (2953d95d40 (The eighth batch, 2024-03-15)), to avoid conflicts
in 'Documentation/config/advice.txt' due to Kristoffer's merged series

Changes since v1:
- renamed the new advice to 'advice.mergeConflict' to make it non-sequencer
  specific
- added 2/2 which uses the advice in builtin/am, which covers
  'git rebase --apply' and 'git am'

Note that the code path where 'git rebase --apply' stops because of conflicts
is not covered by the tests but I tested it manually using this diff:
```
diff --git a/t/t5520-pull.sh b/t/t5520-pull.sh
index 47534f1062..34eac2e6f4 100755
--- a/t/t5520-pull.sh
+++ b/t/t5520-pull.sh
@@ -374,7 +374,7 @@ test_pull_autostash_fail ()
 	echo conflicting >>seq.txt &&
 	test_tick &&
 	git commit -m "Create conflict" seq.txt &&
-	test_must_fail git pull --rebase . seq 2>err >out &&
+	test_must_fail git -c rebase.backend=apply pull --rebase . seq 2>err >out &&
 	test_grep "Resolve all conflicts manually" err
 '
```

CC: Elijah Newren <newren@gmail.com>
CC: Phillip Wood <phillip.wood@dunelm.org.uk>
CC: Johannes Schindelin <Johannes.Schindelin@gmx.de>
CC: ZheNing Hu <adlternative@gmail.com>
cc: "Kristoffer Haugsbakk" <code@khaugsbakk.name>
cc: Rubén Justo <rjusto@gmail.com>
cc: Phillip Wood <phillip.wood123@gmail.com>

### CODE REVIEW

**Comment by phil-blain** [comment]
@dscho, @webstech: not sure what happened here but the CC trailers in the PR description did not make it through as CCs, they were left as-is in the in-patch commentary here: https://lore.kernel.org/git/pull.1682.git.1709396291693.gitgitgadget@gmail.com/T/#u

**Comment by dscho** [comment]
> not sure what happened here

I guess it's because there was _no_ cover letter body. GitGitGadget was simply not designed that way ;-)

It'd probably be relatively easy to [adjust the code that expects an empty line before the `Cc:` footers](https://github.com/gitgitgadget/gitgitgadget/blob/6425a8ef9ef28874fecac03d43d7a10492d42355/lib/patch-series.ts#L207-L208). Go ahead if you want to give it a try; I'll be honest and state that I won't be able to take care of that for you.

**Pull request closed without merging**
