### PR TITLE
rebase: swap command-line options in documentation

### PR DESCRIPTION
**Pull request by Calinou**
I wasted an hour because I thought I'd have to specify "good" then "bad" since I followed the order of the options instead of the positional arguments. Let's make this harder to happen in the future :)

### CODE REVIEW

**Comment by dscho** [comment]
> rebase: swap command-line options in documentation

Did you mean "bisect" instead of "rebase"?

**Comment by Calinou** [comment]
> Did you mean "bisect" instead of "rebase"?

Good catch. I followed the tutorial a bit too closely :wink:

**Pull request closed without merging**
